"""
modules/public_proof_adapter.py  v1.4.0
The public proof log: legacy systems send sebbi.pro the SHA-256 of a state
change, and get back a receipt proving that hash is in an append-only log.

  * An RFC 6962 Merkle tree (the Certificate Transparency construction):
        leaf hash  = SHA-256(0x00 || entry)      entry = the 32-byte state hash
        node hash  = SHA-256(0x01 || left || right)
    so any receipt can be checked by anyone, with any RFC 6962 verifier,
    without trusting this server.
  * Receipts come back straight away: leaf index, tree size, root and the
    inclusion (audit) path.
  * Tree heads are sealed into the sebbi.pro chain on a schedule (every 60s or
    every 1,000 leaves, whichever comes first). That chain is walkable at
    /x/walk and its tip is timestamped in Bitcoin with OpenTimestamps by the
    existing anchor, so a leaf becomes Bitcoin-anchored once a confirmed
    anchored tip is at or after the block that sealed its tree head.
  * Hash-only. No payloads, labels or customer data are sent or stored.
  * Idempotent: the client sends its own id with each hash, so a retry after a
    lost response returns the original leaf instead of adding a duplicate.

Routes (clean /p/ prefix, armed by /x/public_proof_adapter/status):

    POST /p/submit        {"items":[{"hash":"<64 hex>","cid":"<client id>"}]}
                          or {"hash":"<64 hex>"}      needs an API key
    GET  /p/receipt?leaf=N        receipt against the sealed tree head
    GET  /p/proof?leaf=N&size=M   inclusion path at tree size M
    GET  /p/consistency?first=M&second=N   RFC 6962 consistency proof
    GET  /p/sth                   latest sealed tree head + current size
    GET  /p/find?hash=<64 hex>    leaf indexes holding that entry hash
    GET  /p/                      what this log is and how to check it

Pages and downloads (1.1.0), reached from the "plug in" bubble on the homepage:

    GET  /plugin                  the customer page: two lines, downloads,
                                  live log counts, check a receipt in the browser
    GET  /p/sebbi_adapter.py      the client file customers drop beside their app
    GET  /p/example_legacy_app.py the worked example

Billing (1.4.0): the same meter as the engine - 50p per device per month.
Each fingerprint can say which device it is about (a phone, terminal, till,
car...), sent as a one-way hash. Every distinct device seen on the key in a
calendar month counts once, through server.py's own record_device(), so a
customer running one central server for 20 million phones is billed for 20
million devices. Fingerprints with no device named count the installation
that sent them. Free for the key's 90-day trial. When a key's trial ends unpaid, /p/submit
answers 402 with the same Stripe checkout the engine gives (server.py's own
trial_checkout, quantity = real devices). Receipts, proofs and every GET route
stay free for good; the client keeps queuing and sends once paid.

The API key goes in the X-Sebbi-Key header (or "key" in the body). Set
ADAPTER_OPEN=1 in Railway to accept submissions without a key (not advised).

Loading: the live server loads modules through modules/router.py and calls
handle(). ALIASES and register(MODULE_MAP) are also provided so a loader that
maps modules by name (e.g. brain.py) can pick it up under "adapter",
"sidecar" or "anchor".

Assumes one server process (as on Railway today). If a second process ever
writes the same database, appends detect it and reload before continuing.
"""

import base64
import hashlib
import json
import os
import re
import sqlite3
import sys
import threading
import time
import urllib.parse

VERSION = "1.4.0"
ALIASES = ["adapter", "sidecar", "anchor"]
PUBLIC = {("GET", "status"), ("GET", "spec"), ("GET", "sth"), ("GET", "proof"),
          ("GET", "receipt"), ("GET", "consistency"), ("GET", "find")}

KEY = "public-proof-adapter"
SITE = "https://sebbi.pro"
MAX_ITEMS = 500
MAX_BODY = 262144
CHECKPOINT_SECONDS = max(10, int(os.environ.get("ADAPTER_CHECKPOINT_SECONDS", "60") or 60))
CHECKPOINT_EVERY = max(1, int(os.environ.get("ADAPTER_CHECKPOINT_EVERY", "1000") or 1000))
OPEN = os.environ.get("ADAPTER_OPEN", "0") == "1"
HEX64 = re.compile(r"^[0-9a-f]{64}$")
CID_RE = re.compile(r"^[A-Za-z0-9_.:-]{1,80}$")
SPEC = ("RFC 6962 Merkle tree, SHA-256. leaf_hash = SHA256(0x00 || entry); "
        "node = SHA256(0x01 || left || right); entry = the 32 raw bytes of the submitted hash.")

_PAGE_B64 = (
    "PCFET0NUWVBFIGh0bWw+PGh0bWwgbGFuZz0iZW4iPjxoZWFkPjxtZXRhIGNoYXJzZXQ9IlVURi04Ij4KPG1ldGEgbmFtZT0idmll"
    "d3BvcnQiIGNvbnRlbnQ9IndpZHRoPWRldmljZS13aWR0aCxpbml0aWFsLXNjYWxlPTEsdmlld3BvcnQtZml0PWNvdmVyIj4KPHRp"
    "dGxlPlBsdWcgaW4g4oCUIHNlYmJpLnBybzwvdGl0bGU+CjxtZXRhIG5hbWU9ImRlc2NyaXB0aW9uIiBjb250ZW50PSJUd28gbGlu"
    "ZXMgb2YgUHl0aG9uIGFuZCBldmVyeSBjaGFuZ2UgeW91ciBzeXN0ZW0gbWFrZXMgZ2V0cyBhIHJlY2VpcHQgYW55b25lIGNhbiBj"
    "aGVjay4gS2VlcCB5b3VyIHN0YWNrLiBBZGQgdGhlIHByb29mLiI+CjxsaW5rIGhyZWY9Imh0dHBzOi8vZm9udHMuZ29vZ2xlYXBp"
    "cy5jb20vY3NzMj9mYW1pbHk9SUJNK1BsZXgrTW9ubzp3Z2h0QDQwMDs1MDA7NjAwJmZhbWlseT1JQk0rUGxleCtTYW5zOndnaHRA"
    "NDAwOzUwMDs2MDAmZmFtaWx5PU5ld3NyZWFkZXI6b3Bzeix3Z2h0QDYuLjcyLDUwMCZkaXNwbGF5PXN3YXAiIHJlbD0ic3R5bGVz"
    "aGVldCI+CjxzdHlsZT4KOnJvb3R7LS1pbms6IzA1MDcwZjstLWdvbGQ6I2M5YTg0YzstLW9rOiM3ZmUzYjA7LS1ibHVlOiM4ZmQw"
    "ZmY7LS1tdXRlOiM4YTkzYWQ7LS1saW5lOnJnYmEoMTQzLDIwOCwyNTUsLjIyKTsKLS1tb25vOidJQk0gUGxleCBNb25vJyx1aS1t"
    "b25vc3BhY2UsbW9ub3NwYWNlOy0tc2FuczonSUJNIFBsZXggU2Fucycsc3lzdGVtLXVpLHNhbnMtc2VyaWY7LS1zZXJpZjonTmV3"
    "c3JlYWRlcicsR2VvcmdpYSxzZXJpZn0KKntib3gtc2l6aW5nOmJvcmRlci1ib3g7bWFyZ2luOjA7cGFkZGluZzowOy13ZWJraXQt"
    "dGFwLWhpZ2hsaWdodC1jb2xvcjp0cmFuc3BhcmVudH0KYm9keXtiYWNrZ3JvdW5kOnJhZGlhbC1ncmFkaWVudChlbGxpcHNlIGF0"
    "IDUwJSAwJSwjMTAyMzNlLCMwNTA3MGYgNjIlKTtjb2xvcjojZThlZGY3O2ZvbnQtZmFtaWx5OnZhcigtLXNhbnMpO2xpbmUtaGVp"
    "Z2h0OjEuNjttaW4taGVpZ2h0OjEwMHZofQoud3JhcHttYXgtd2lkdGg6NzYwcHg7bWFyZ2luOjAgYXV0bztwYWRkaW5nOjAgMjBw"
    "eCA4MHB4fQoudG9we2Rpc3BsYXk6ZmxleDtqdXN0aWZ5LWNvbnRlbnQ6c3BhY2UtYmV0d2VlbjthbGlnbi1pdGVtczpjZW50ZXI7"
    "cGFkZGluZzpjYWxjKDE0cHggKyBlbnYoc2FmZS1hcmVhLWluc2V0LXRvcCkpIDAgMH0KLmJyYW5ke2ZvbnQtZmFtaWx5OnZhcigt"
    "LW1vbm8pO2ZvbnQtc2l6ZToxM3B4fS5icmFuZCBie2NvbG9yOnZhcigtLWJsdWUpO2ZvbnQtd2VpZ2h0OjUwMH0KLnRvcCBhe2Zv"
    "bnQtZmFtaWx5OnZhcigtLW1vbm8pO2ZvbnQtc2l6ZToxMnB4O2NvbG9yOnZhcigtLW11dGUpO3RleHQtZGVjb3JhdGlvbjpub25l"
    "O21hcmdpbi1sZWZ0OjE0cHh9Cmgxe2ZvbnQtZmFtaWx5OnZhcigtLXNlcmlmKTtmb250LXdlaWdodDo1MDA7Zm9udC1zaXplOmNs"
    "YW1wKDMycHgsN3Z3LDU0cHgpO2xpbmUtaGVpZ2h0OjEuMDg7bWFyZ2luOjMwcHggMCAxMnB4fQpoMntmb250LWZhbWlseTp2YXIo"
    "LS1zZXJpZik7Zm9udC13ZWlnaHQ6NTAwO2ZvbnQtc2l6ZToyNHB4O21hcmdpbjowIDAgOHB4fQpwLmxlYWR7Y29sb3I6I2I2YzBk"
    "Njtmb250LXNpemU6MTdweDttYXgtd2lkdGg6NTRjaH0KLmxpdmV7ZGlzcGxheTpmbGV4O2dhcDoxMHB4O21hcmdpbjoyNHB4IDAg"
    "OHB4O2ZsZXgtd3JhcDp3cmFwfQouc3RhdHtmbGV4OjE7bWluLXdpZHRoOjE0MHB4O2JhY2tncm91bmQ6cmdiYSgxMywyMCwzNiwu"
    "ODUpO2JvcmRlcjoxcHggc29saWQgdmFyKC0tbGluZSk7Ym9yZGVyLXJhZGl1czoxNHB4O3BhZGRpbmc6MTRweCAxNnB4fQouc3Rh"
    "dCBie2Rpc3BsYXk6YmxvY2s7Zm9udDo2MDAgMjZweCB2YXIoLS1tb25vKTtjb2xvcjp2YXIoLS1vayk7Zm9udC12YXJpYW50LW51"
    "bWVyaWM6dGFidWxhci1udW1zfQouc3RhdCBzcGFue2ZvbnQ6NTAwIDEycHggdmFyKC0tbW9ubyk7Y29sb3I6dmFyKC0tbXV0ZSl9"
    "Ci5jYXJke2JhY2tncm91bmQ6cmdiYSgxMywyMCwzNiwuOCk7Ym9yZGVyOjFweCBzb2xpZCB2YXIoLS1saW5lKTtib3JkZXItcmFk"
    "aXVzOjE2cHg7cGFkZGluZzoyMHB4O21hcmdpbi10b3A6MTZweH0KLmNhcmQgcHtjb2xvcjojYjZjMGQ2O2ZvbnQtc2l6ZToxNXB4"
    "fQpwcmV7bWFyZ2luLXRvcDoxMnB4O2JhY2tncm91bmQ6IzAzMDUwYjtib3JkZXI6MXB4IHNvbGlkIHJnYmEoMjU1LDI1NSwyNTUs"
    "LjA4KTtib3JkZXItcmFkaXVzOjEycHg7cGFkZGluZzoxNHB4IDE2cHg7b3ZlcmZsb3cteDphdXRvOwpmb250OjEzLjVweC8xLjYg"
    "dmFyKC0tbW9ubyk7Y29sb3I6I2RmZThmNX0KcHJlIC5je2NvbG9yOnZhcigtLW11dGUpfXByZSAua3tjb2xvcjp2YXIoLS1ibHVl"
    "KX1wcmUgLnN7Y29sb3I6dmFyKC0tb2spfQouc3RlcHN7Y291bnRlci1yZXNldDpzO2xpc3Qtc3R5bGU6bm9uZTttYXJnaW4tdG9w"
    "OjEwcHh9Ci5zdGVwcyBsaXtjb3VudGVyLWluY3JlbWVudDpzO3Bvc2l0aW9uOnJlbGF0aXZlO3BhZGRpbmc6MTBweCAwIDEwcHgg"
    "NDBweDtib3JkZXItdG9wOjFweCBzb2xpZCByZ2JhKDI1NSwyNTUsMjU1LC4wNik7Y29sb3I6I2NmZDhlYTtmb250LXNpemU6MTVw"
    "eH0KLnN0ZXBzIGxpOmZpcnN0LWNoaWxke2JvcmRlci10b3A6MH0KLnN0ZXBzIGxpOmJlZm9yZXtjb250ZW50OmNvdW50ZXIocyk7"
    "cG9zaXRpb246YWJzb2x1dGU7bGVmdDowO3RvcDoxMHB4O3dpZHRoOjI2cHg7aGVpZ2h0OjI2cHg7Ym9yZGVyLXJhZGl1czo4cHg7"
    "YmFja2dyb3VuZDp2YXIoLS1ibHVlKTsKY29sb3I6IzA1MDcwZjtmb250OjYwMCAxM3B4IHZhcigtLW1vbm8pO2Rpc3BsYXk6Z3Jp"
    "ZDtwbGFjZS1pdGVtczpjZW50ZXJ9Ci5idG5ze2Rpc3BsYXk6ZmxleDtmbGV4LXdyYXA6d3JhcDtnYXA6MTBweDttYXJnaW4tdG9w"
    "OjE2cHh9Ci5idG57ZGlzcGxheTppbmxpbmUtZmxleDthbGlnbi1pdGVtczpjZW50ZXI7Z2FwOjhweDtwYWRkaW5nOjEzcHggMThw"
    "eDtib3JkZXItcmFkaXVzOjEycHg7Zm9udDo2MDAgMTMuNXB4IHZhcigtLW1vbm8pO3RleHQtZGVjb3JhdGlvbjpub25lOwpiYWNr"
    "Z3JvdW5kOnZhcigtLWJsdWUpO2NvbG9yOiMwNTA3MGY7Ym9yZGVyOjA7Y3Vyc29yOnBvaW50ZXJ9Ci5idG4uZ2hvc3R7YmFja2dy"
    "b3VuZDp0cmFuc3BhcmVudDtjb2xvcjojZmZmO2JvcmRlcjoxcHggc29saWQgcmdiYSgyNTUsMjU1LDI1NSwuMjQpfQouYnRuOmZv"
    "Y3VzLXZpc2libGUsaW5wdXQ6Zm9jdXMtdmlzaWJsZXtvdXRsaW5lOjJweCBzb2xpZCB2YXIoLS1vayk7b3V0bGluZS1vZmZzZXQ6"
    "M3B4fQouZ3JpZHtkaXNwbGF5OmdyaWQ7Z3JpZC10ZW1wbGF0ZS1jb2x1bW5zOjFmcjtnYXA6MTJweDttYXJnaW4tdG9wOjEycHh9"
    "CkBtZWRpYShtaW4td2lkdGg6NjIwcHgpey5ncmlke2dyaWQtdGVtcGxhdGUtY29sdW1uczoxZnIgMWZyfX0KLmdyaWQgZGl2e2Jh"
    "Y2tncm91bmQ6cmdiYSgyNTUsMjU1LDI1NSwuMDMpO2JvcmRlcjoxcHggc29saWQgcmdiYSgyNTUsMjU1LDI1NSwuMDcpO2JvcmRl"
    "ci1yYWRpdXM6MTJweDtwYWRkaW5nOjE0cHh9Ci5ncmlkIGJ7ZGlzcGxheTpibG9jaztmb250OjYwMCAxNHB4IHZhcigtLW1vbm8p"
    "O2NvbG9yOiNmZmY7bWFyZ2luLWJvdHRvbTo0cHh9LmdyaWQgc3Bhbntmb250LXNpemU6MTRweDtjb2xvcjojYjZjMGQ2fQoucm93"
    "e2Rpc3BsYXk6ZmxleDtnYXA6MTBweDttYXJnaW4tdG9wOjEycHh9CmlucHV0e2ZsZXg6MTttaW4td2lkdGg6MDtwYWRkaW5nOjEz"
    "cHggMTRweDtib3JkZXItcmFkaXVzOjEycHg7Ym9yZGVyOjFweCBzb2xpZCByZ2JhKDI1NSwyNTUsMjU1LC4xOCk7YmFja2dyb3Vu"
    "ZDojMDMwNTBiO2NvbG9yOiNmZmY7Zm9udDoxNXB4IHZhcigtLW1vbm8pfQoub3V0e21hcmdpbi10b3A6MTRweDtmb250OjEzcHgv"
    "MS42IHZhcigtLW1vbm8pO2NvbG9yOiNjZmU2ZDk7ZGlzcGxheTpub25lO3dvcmQtYnJlYWs6YnJlYWstYWxsfQoub3V0Lm9ue2Rp"
    "c3BsYXk6YmxvY2t9LnBhc3N7Y29sb3I6dmFyKC0tb2spO2ZvbnQtd2VpZ2h0OjYwMH0uZmFpbHtjb2xvcjojZmY4YTgwO2ZvbnQt"
    "d2VpZ2h0OjYwMH0KLm91dCBhe2NvbG9yOnZhcigtLWJsdWUpfQoucHJpY2V7ZGlzcGxheTpmbGV4O2FsaWduLWl0ZW1zOmNlbnRl"
    "cjtnYXA6MTRweDtmbGV4LXdyYXA6d3JhcDttYXJnaW46MjBweCAwIDRweDtwYWRkaW5nOjE2cHggMThweDtib3JkZXItcmFkaXVz"
    "OjE2cHg7CmJhY2tncm91bmQ6cmdiYSgxNDMsMjA4LDI1NSwuMDgpO2JvcmRlcjoxcHggc29saWQgdmFyKC0tbGluZSl9Ci5wcmlj"
    "ZSBie2ZvbnQ6NjAwIDQwcHggdmFyKC0tbW9ubyk7Y29sb3I6dmFyKC0tb2spO2xpbmUtaGVpZ2h0OjF9LnByaWNlIHNwYW57Zm9u"
    "dDo1MDAgMTNweC8xLjQgdmFyKC0tbW9ubyk7Y29sb3I6I2NmZDhlYTtmbGV4OjE7bWluLXdpZHRoOjE1MHB4fQoucHJpY2UgLmJ0"
    "bnttYXJnaW46MH0KLmNhbGN7bWFyZ2luLXRvcDoxNHB4O2ZvbnQ6MTVweCB2YXIoLS1tb25vKTtjb2xvcjojY2ZkOGVhfS5jYWxj"
    "IGxhYmVse2Rpc3BsYXk6YmxvY2s7Zm9udC1zaXplOjEycHg7Y29sb3I6dmFyKC0tbXV0ZSk7bWFyZ2luLWJvdHRvbTo2cHh9Ci5j"
    "YWxjIGlucHV0e3dpZHRoOjEwMCU7YWNjZW50LWNvbG9yOiM4ZmQwZmY7cGFkZGluZzowO2JvcmRlcjowO2JhY2tncm91bmQ6bm9u"
    "ZX0uY2FsYyBie2NvbG9yOnZhcigtLW9rKX0KLnNtYWxse2ZvbnQtc2l6ZToxM3B4IWltcG9ydGFudDtjb2xvcjp2YXIoLS1tdXRl"
    "KSFpbXBvcnRhbnQ7bWFyZ2luLXRvcDoxMHB4fQo8L3N0eWxlPjwvaGVhZD48Ym9keT48ZGl2IGNsYXNzPSJ3cmFwIj4KPGRpdiBj"
    "bGFzcz0idG9wIj48ZGl2IGNsYXNzPSJicmFuZCI+c2ViYmk8Yj4ucHJvPC9iPiDCtyBQTFVHIElOPC9kaXY+PG5hdj48YSBocmVm"
    "PSIvc3RhcnQiPlN0YXJ0PC9hPjxhIGhyZWY9Ii9wcm92ZSI+UHJvb2Y8L2E+PGEgaHJlZj0iLyI+SG9tZTwvYT48L25hdj48L2Rp"
    "dj4KCjxoMT5LZWVwIHlvdXIgc3lzdGVtLjxicj5BZGQgdGhlIHByb29mLjwvaDE+CjxwIGNsYXNzPSJsZWFkIj5Ud28gbGluZXMg"
    "b2YgUHl0aG9uIGFuZCBldmVyeSBjaGFuZ2UgeW91ciBzeXN0ZW0gbWFrZXMgZ2V0cyBhIHJlY2VpcHQgYW55b25lIGNhbiBjaGVj"
    "ay4gU2FtZSBkYXRhYmFzZSwgc2FtZSBjb2RlLCBzYW1lIHNlcnZlcnMuIE9ubHkgYSBmaW5nZXJwcmludCB0cmF2ZWxzOyB5b3Vy"
    "IGRhdGEgc3RheXMgZXhhY3RseSB3aGVyZSBpdCBpcy48L3A+CjxkaXYgY2xhc3M9InByaWNlIj48Yj41MHA8L2I+PHNwYW4+cGVy"
    "IGRldmljZSBwZXIgbW9udGg8YnI+ZXZlcnkgcGhvbmUsIHRpbGwgb3IgbWFjaGluZSB5b3UgcmVjb3JkIGZvcjxicj5mcmVlIGZv"
    "ciB5b3VyIGZpcnN0IDkwIGRheXM8L3NwYW4+PGEgY2xhc3M9ImJ0biIgaHJlZj0iL3N0YXJ0Ij5TdGFydCBmcmVlPC9hPjwvZGl2"
    "PgoKPGRpdiBjbGFzcz0ibGl2ZSIgaWQ9ImxpdmUiPgogPGRpdiBjbGFzcz0ic3RhdCI+PGIgaWQ9InNpemUiPuKAlDwvYj48c3Bh"
    "bj5lbnRyaWVzIGluIHRoZSBwdWJsaWMgbG9nPC9zcGFuPjwvZGl2PgogPGRpdiBjbGFzcz0ic3RhdCI+PGIgaWQ9InNlYWxlZCI+"
    "4oCUPC9iPjxzcGFuPmxhc3QgdHJlZSBoZWFkIHNlYWxlZCBpbiBibG9jazwvc3Bhbj48L2Rpdj4KPC9kaXY+Cgo8ZGl2IGNsYXNz"
    "PSJjYXJkIj4KIDxoMj5UaGUgdHdvIGxpbmVzPC9oMj4KIDxwPlB1dCB0aGUgaW1wb3J0IGF0IHRoZSB0b3AgYW5kIHRoZSBsaW5l"
    "IGFib3ZlIGFueSBmdW5jdGlvbiB0aGF0IGNoYW5nZXMgc29tZXRoaW5nIGltcG9ydGFudC4gSXQgY2FycmllcyBvbiB3b3JraW5n"
    "IGV4YWN0bHkgYXMgYmVmb3JlLjwvcD4KPHByZT48c3BhbiBjbGFzcz0iayI+ZnJvbTwvc3Bhbj4gc2ViYmlfYWRhcHRlciA8c3Bh"
    "biBjbGFzcz0iayI+aW1wb3J0PC9zcGFuPiBhbmNob3Jfc3RhdGUKPHNwYW4gY2xhc3M9ImsiPkBhbmNob3Jfc3RhdGU8L3NwYW4+"
    "KDxzcGFuIGNsYXNzPSJzIj4ib3JkZXJzLnVwZGF0ZSI8L3NwYW4+LCBkZXZpY2U9PHNwYW4gY2xhc3M9InMiPiJoYW5kc2V0Ijwv"
    "c3Bhbj4pCjxzcGFuIGNsYXNzPSJrIj5kZWY8L3NwYW4+IHVwZGF0ZV9vcmRlcihvcmRlcl9pZCwgc3RhdHVzLCBoYW5kc2V0KToK"
    "ICAgIC4uLiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxzcGFuIGNsYXNzPSJjIj4jIHlvdXIgY29kZSwgdW5jaGFuZ2Vk"
    "PC9zcGFuPgogICAgPHNwYW4gY2xhc3M9ImsiPnJldHVybjwvc3Bhbj4gezxzcGFuIGNsYXNzPSJzIj4ib3JkZXJfaWQiPC9zcGFu"
    "Pjogb3JkZXJfaWQsIDxzcGFuIGNsYXNzPSJzIj4ic3RhdHVzIjwvc3Bhbj46IHN0YXR1c308L3ByZT4KIDxvbCBjbGFzcz0ic3Rl"
    "cHMiPgogIDxsaT5Eb3dubG9hZCA8Yj5zZWJiaV9hZGFwdGVyLnB5PC9iPiBhbmQgcHV0IGl0IG5leHQgdG8geW91ciBjb2RlLiBO"
    "byBpbnN0YWxscywgbm90aGluZyBlbHNlIHRvIGFkZC48L2xpPgogIDxsaT5TZXQgeW91ciBzZWJiaS5wcm8ga2V5OiA8Y29kZT5T"
    "RUJCSV9BUElfS0VZPXlvdXIta2V5PC9jb2RlPjwvbGk+CiAgPGxpPkFkZCB0aGUgZGVjb3JhdG9yLCBhbmQgbmFtZSB0aGUgZGV2"
    "aWNlIGVhY2ggY2hhbmdlIGlzIGFib3V0LiBSZWNlaXB0cyBhcnJpdmUgaW4gdGhlIGJhY2tncm91bmQgZnJvbSB0aGVuIG9uLjwv"
    "bGk+CiA8L29sPgogPGRpdiBjbGFzcz0iYnRucyI+CiAgPGEgY2xhc3M9ImJ0biIgaHJlZj0iL3Avc2ViYmlfYWRhcHRlci5weSIg"
    "ZG93bmxvYWQ+RG93bmxvYWQgc2ViYmlfYWRhcHRlci5weTwvYT4KICA8YSBjbGFzcz0iYnRuIGdob3N0IiBocmVmPSIvcC9leGFt"
    "cGxlX2xlZ2FjeV9hcHAucHkiIGRvd25sb2FkPldvcmtlZCBleGFtcGxlPC9hPgogIDxhIGNsYXNzPSJidG4gZ2hvc3QiIGhyZWY9"
    "Ii9zdGFydCI+R2V0IGEga2V5PC9hPgogPC9kaXY+CjwvZGl2PgoKPGRpdiBjbGFzcz0iY2FyZCI+CiA8aDI+QnVpbHQgZm9yIHRo"
    "ZSByZWNvcmRzIHRoYXQgbWF0dGVyPC9oMj4KIDxkaXYgY2xhc3M9ImdyaWQiPgogIDxkaXY+PGI+UGF5bWVudHMgJmFtcDsgYmFs"
    "YW5jZXM8L2I+PHNwYW4+RXZlcnkgZGViaXQsIGNyZWRpdCBhbmQgcmVmdW5kIGNhcnJpZXMgaXRzIG93biByZWNlaXB0LiBQcm92"
    "ZSB3aGF0IGEgYmFsYW5jZSB3YXMsIGFuZCB3aGVuLjwvc3Bhbj48L2Rpdj4KICA8ZGl2PjxiPkFJIGRlY2lzaW9uczwvYj48c3Bh"
    "bj5GaW5nZXJwcmludCB3aGF0IHRoZSBtb2RlbCBkZWNpZGVkIGFuZCB3aHksIHRoZSBtb21lbnQgaXQgZGVjaWRlcy4gVGhlIEVV"
    "IEFJIEFjdCBhc2tzIGZvciBleGFjdGx5IHRoaXMgcmVjb3JkLjwvc3Bhbj48L2Rpdj4KICA8ZGl2PjxiPk9yZGVycyAmYW1wOyBz"
    "dG9jazwvYj48c3Bhbj5FdmVyeSBzdGF0dXMgY2hhbmdlIG9uIHRoZSByZWNvcmQsIGluIG9yZGVyLCBwcm92YWJsZSB0byBhIGN1"
    "c3RvbWVyLCBzdXBwbGllciBvciBjb3VydC48L3NwYW4+PC9kaXY+CiAgPGRpdj48Yj5IZWFsdGggJmFtcDsgbGVnYWwgZmlsZXM8"
    "L2I+PHNwYW4+UHJvdmUgYSByZWNvcmQgaGFzbid0IGNoYW5nZWQgc2luY2UgdGhlIGRheSBpdCB3YXMgd3JpdHRlbiwgd2l0aG91"
    "dCBldmVyIHNlbmRpbmcgdGhlIHJlY29yZCBhbnl3aGVyZS48L3NwYW4+PC9kaXY+CiAgPGRpdj48Yj5Mb2dzICZhbXA7IGF1ZGl0"
    "IHRyYWlsczwvYj48c3Bhbj5QbHVnIGl0IGludG8geW91ciBleGlzdGluZyBsb2dnZXIgYW5kIGV2ZXJ5IGxpbmUgYmVjb21lcyBl"
    "dmlkZW5jZSBub2JvZHkgY2FuIHF1aWV0bHkgZWRpdC48L3NwYW4+PC9kaXY+CiAgPGRpdj48Yj5Bbnl0aGluZyB5b3UnZCBkZWZl"
    "bmQ8L2I+PHNwYW4+SWYgeW91J2QgZXZlciBuZWVkIHRvIHNob3cgd2hhdCB5b3VyIHN5c3RlbSBkaWQsIGFuZCB3aGVuLCBpdCBi"
    "ZWxvbmdzIGhlcmUuPC9zcGFuPjwvZGl2PgogPC9kaXY+CjwvZGl2PgoKPGRpdiBjbGFzcz0iY2FyZCI+CiA8aDI+T25lIHByaWNl"
    "IHBlciBkZXZpY2UsIGhvd2V2ZXIgbXVjaCBpdCByZWNvcmRzPC9oMj4KIDxwPkV2ZXJ5IHBob25lLCB0aWxsLCB0ZXJtaW5hbCBv"
    "ciBtYWNoaW5lIHlvdXIgc3lzdGVtIHJlY29yZHMgZm9yIGlzIG9uZSBkZXZpY2UsIGNvdW50ZWQgb25jZSBhIG1vbnRoLCB3aGV0"
    "aGVyIGl0IG1ha2VzIHRlbiBjaGFuZ2VzIG9yIHRlbiBtaWxsaW9uLiBSdW4gaXQgb24gb25lIHNlcnZlciBvciBhIHRob3VzYW5k"
    "OiB0aGUgY291bnQgaXMgdGhlIGRldmljZXMsIG5vdCB0aGUgc2VydmVycy48L3A+CiA8ZGl2IGNsYXNzPSJjYWxjIj48bGFiZWwg"
    "Zm9yPSJkZXYiPkRldmljZXM8L2xhYmVsPjxpbnB1dCBpZD0iZGV2IiB0eXBlPSJyYW5nZSIgbWluPSIwIiBtYXg9IjEwMCIgdmFs"
    "dWU9IjMwIiBhcmlhLWxhYmVsPSJEZXZpY2VzIj48ZGl2PjxiIGlkPSJkZXZuIj4yMDwvYj4gZGV2aWNlcyA9IDxiIGlkPSJjb3N0"
    "Ij7CozEwLjAwPC9iPiBhIG1vbnRoPC9kaXY+PC9kaXY+CiA8cCBjbGFzcz0ic21hbGwiPkZyb20gb25lIGRldmljZSB0byB0ZW4g"
    "bWlsbGlvbi4gRnJlZSBmb3IgdGhlIGZpcnN0IDkwIGRheXMgb24gYSBuZXcga2V5LCBubyBjYXJkIHRvIHN0YXJ0LiBSZWNlaXB0"
    "cyBhbmQgcHJvb2ZzIHN0YXkgeW91cnMgZm9yIGdvb2QuPC9wPgo8L2Rpdj4KCjxkaXYgY2xhc3M9ImNhcmQiPgogPGgyPldoYXQg"
    "eW91IGdldDwvaDI+CiA8ZGl2IGNsYXNzPSJncmlkIj4KICA8ZGl2PjxiPk5ldmVyIHNsb3dzIHlvdSBkb3duPC9iPjxzcGFuPkZp"
    "bmdlcnByaW50cyBxdWV1ZSBvbiB5b3VyIG93biBtYWNoaW5lIGFuZCBzZW5kIGluIHRoZSBiYWNrZ3JvdW5kLiBZb3VyIGFwcCBu"
    "ZXZlciB3YWl0cyBvbiB0aGUgbmV0d29yay48L3NwYW4+PC9kaXY+CiAgPGRpdj48Yj5LZWVwcyBnb2luZyBvZmZsaW5lPC9iPjxz"
    "cGFuPklmIHNlYmJpLnBybyBjYW4ndCBiZSByZWFjaGVkLCBldmVyeXRoaW5nIHdhaXRzIHNhZmVseSBhbmQgc2VuZHMgaW4gb3Jk"
    "ZXIgd2hlbiBpdCdzIGJhY2suIE5vdGhpbmcgbG9zdCwgbm90aGluZyBkb3VibGVkLjwvc3Bhbj48L2Rpdj4KICA8ZGl2PjxiPkNo"
    "ZWNrcyB0aGUgYW5zd2VyPC9iPjxzcGFuPkV2ZXJ5IHJlY2VpcHQgaXMgdmVyaWZpZWQgb24geW91ciBzaWRlIHRoZSBtb21lbnQg"
    "aXQgYXJyaXZlcywgc28geW91J3JlIG5vdCB0YWtpbmcgb3VyIHdvcmQgZm9yIGl0Ljwvc3Bhbj48L2Rpdj4KICA8ZGl2PjxiPkFu"
    "Y2hvcmVkIGluIEJpdGNvaW48L2I+PHNwYW4+VGhlIGxvZyBpcyBzZWFsZWQgaW50byB0aGUgc2ViYmkucHJvIGNoYWluIGV2ZXJ5"
    "IG1pbnV0ZSwgYW5kIHRoZSBjaGFpbiBpcyB0aW1lc3RhbXBlZCBpbiBCaXRjb2luLjwvc3Bhbj48L2Rpdj4KICA8ZGl2PjxiPlN0"
    "YW5kYXJkIHByb29mczwvYj48c3Bhbj5UaGUgc2FtZSBNZXJrbGUtdHJlZSByZWNlaXB0cyB0aGF0IHNlY3VyZSB3ZWIgY2VydGlm"
    "aWNhdGVzIChSRkMgNjk2MikuIEFueSBjb21wYXRpYmxlIGNoZWNrZXIgY2FuIHZlcmlmeSB0aGVtLjwvc3Bhbj48L2Rpdj4KICA8"
    "ZGl2PjxiPldvcmtzIHdpdGggYW55dGhpbmc8L2I+PHNwYW4+RGF0YWJhc2Ugd3JpdGVzLCBBUEkgaGFuZGxlcnMsIGFzeW5jIGNv"
    "ZGUgYW5kIHlvdXIgZXhpc3RpbmcgbG9nZ2Vycy4gUHl0aG9uIDMuOCBhbmQgdXAuPC9zcGFuPjwvZGl2PgogPC9kaXY+CjwvZGl2"
    "PgoKPGRpdiBjbGFzcz0iY2FyZCIgaWQ9ImNoZWNrIj4KIDxoMj5DaGVjayBhIHJlY2VpcHQ8L2gyPgogPHA+VHlwZSBhbiBlbnRy"
    "eSBudW1iZXIuIFlvdXIgYnJvd3NlciBmZXRjaGVzIHRoZSByZWNlaXB0IGFuZCBjaGVja3MgdGhlIG1hdGhzIGl0c2VsZi48L3A+"
    "CiA8ZGl2IGNsYXNzPSJyb3ciPjxpbnB1dCBpZD0ibGVhZiIgaW5wdXRtb2RlPSJudW1lcmljIiBwbGFjZWhvbGRlcj0iRW50cnkg"
    "bnVtYmVyLCBlLmcuIDAiIGFyaWEtbGFiZWw9IkVudHJ5IG51bWJlciI+PGJ1dHRvbiBjbGFzcz0iYnRuIiBpZD0iZ28iPkNoZWNr"
    "PC9idXR0b24+PC9kaXY+CiA8ZGl2IGNsYXNzPSJvdXQiIGlkPSJvdXQiPjwvZGl2Pgo8L2Rpdj4KPC9kaXY+CjxzY3JpcHQ+Cihm"
    "dW5jdGlvbigpewoidXNlIHN0cmljdCI7CmZ1bmN0aW9uICQoaSl7cmV0dXJuIGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKGkpfQpm"
    "dW5jdGlvbiBoZXgyYihoKXt2YXIgYT1uZXcgVWludDhBcnJheShoLmxlbmd0aC8yKTtmb3IodmFyIGk9MDtpPGEubGVuZ3RoO2kr"
    "KylhW2ldPXBhcnNlSW50KGguc3Vic3RyKGkqMiwyKSwxNik7cmV0dXJuIGF9CmZ1bmN0aW9uIGIyaGV4KGIpe3JldHVybiBBcnJh"
    "eS5wcm90b3R5cGUubWFwLmNhbGwobmV3IFVpbnQ4QXJyYXkoYiksZnVuY3Rpb24oeCl7cmV0dXJuKCIwIit4LnRvU3RyaW5nKDE2"
    "KSkuc2xpY2UoLTIpfSkuam9pbigiIil9CmZ1bmN0aW9uIGNhdCgpe3ZhciBuPTAsaTtmb3IoaT0wO2k8YXJndW1lbnRzLmxlbmd0"
    "aDtpKyspbis9YXJndW1lbnRzW2ldLmxlbmd0aDt2YXIgbz1uZXcgVWludDhBcnJheShuKSxwPTA7Zm9yKGk9MDtpPGFyZ3VtZW50"
    "cy5sZW5ndGg7aSsrKXtvLnNldChhcmd1bWVudHNbaV0scCk7cCs9YXJndW1lbnRzW2ldLmxlbmd0aH1yZXR1cm4gb30KZnVuY3Rp"
    "b24gSChiKXtyZXR1cm4gY3J5cHRvLnN1YnRsZS5kaWdlc3QoIlNIQS0yNTYiLGIpLnRoZW4oZnVuY3Rpb24oZCl7cmV0dXJuIG5l"
    "dyBVaW50OEFycmF5KGQpfSl9CmZ1bmN0aW9uIHZlcmlmeShlbnRyeSxpZHgsc2l6ZSxwYXRoLHJvb3QpewogaWYoaWR4PDB8fGlk"
    "eD49c2l6ZSlyZXR1cm4gUHJvbWlzZS5yZXNvbHZlKGZhbHNlKTsKIHZhciBmbj1pZHgsc249c2l6ZS0xOwogcmV0dXJuIEgoY2F0"
    "KG5ldyBVaW50OEFycmF5KFswXSksaGV4MmIoZW50cnkpKSkudGhlbihmdW5jdGlvbihyKXsKICB2YXIgY2hhaW49UHJvbWlzZS5y"
    "ZXNvbHZlKHIpLGJhZD1mYWxzZTsKICBwYXRoLmZvckVhY2goZnVuY3Rpb24ocGgpewogICBjaGFpbj1jaGFpbi50aGVuKGZ1bmN0"
    "aW9uKHIpewogICAgdmFyIHA9aGV4MmIocGgpOwogICAgaWYoc249PT0wKXtiYWQ9dHJ1ZTtyZXR1cm4gcn0KICAgIHZhciBwcjsK"
    "ICAgIGlmKChmbiYxKXx8Zm49PT1zbil7cHI9SChjYXQobmV3IFVpbnQ4QXJyYXkoWzFdKSxwLHIpKTtpZighKGZuJjEpKXt3aGls"
    "ZSghKGZuJjEpJiZmbiE9PTApe2ZuPj49MTtzbj4+PTF9fX0KICAgIGVsc2UgcHI9SChjYXQobmV3IFVpbnQ4QXJyYXkoWzFdKSxy"
    "LHApKTsKICAgIGZuPj49MTtzbj4+PTE7cmV0dXJuIHByfSk7CiAgfSk7CiAgcmV0dXJuIGNoYWluLnRoZW4oZnVuY3Rpb24ocil7"
    "cmV0dXJuICFiYWQmJnNuPT09MCYmYjJoZXgocik9PT1yb290fSk7CiB9KTsKfQp2YXIgZHY9JCgiZGV2Iik7ZnVuY3Rpb24gcHJp"
    "Y2UoKXt2YXIgdj0rZHYudmFsdWUsbj1NYXRoLm1heCgxLE1hdGgucm91bmQoTWF0aC5wb3coMTAsdi8xMDAqNykpKTsKIG49bjwx"
    "MDA/bjoobjwxMDAwMD9NYXRoLnJvdW5kKG4vMTApKjEwOk1hdGgucm91bmQobi8xMDAwKSoxMDAwKTskKCJkZXZuIikudGV4dENv"
    "bnRlbnQ9bi50b0xvY2FsZVN0cmluZygiZW4tR0IiKTsKICQoImNvc3QiKS50ZXh0Q29udGVudD0iwqMiKyhuKjAuNSkudG9Mb2Nh"
    "bGVTdHJpbmcoImVuLUdCIix7bWluaW11bUZyYWN0aW9uRGlnaXRzOjIsbWF4aW11bUZyYWN0aW9uRGlnaXRzOjJ9KX0KZHYuYWRk"
    "RXZlbnRMaXN0ZW5lcigiaW5wdXQiLHByaWNlKTtwcmljZSgpOwpmZXRjaCgiL3Avc3RoIix7Y2FjaGU6Im5vLXN0b3JlIn0pLnRo"
    "ZW4oZnVuY3Rpb24ocil7cmV0dXJuIHIuanNvbigpfSkudGhlbihmdW5jdGlvbihkKXsKICQoInNpemUiKS50ZXh0Q29udGVudD0o"
    "ZC50cmVlX3NpemV8fDApLnRvTG9jYWxlU3RyaW5nKCJlbi1HQiIpOwogdmFyIHM9ZC5sYXRlc3Rfc2VhbGVkX3RyZWVfaGVhZDsk"
    "KCJzZWFsZWQiKS50ZXh0Q29udGVudD1zJiZzLmJsb2NrX2luZGV4IT1udWxsP3MuYmxvY2tfaW5kZXg6IuKAlCI7Cn0pLmNhdGNo"
    "KGZ1bmN0aW9uKCl7fSk7CmZ1bmN0aW9uIHJ1bigpewogdmFyIG49cGFyc2VJbnQoJCgibGVhZiIpLnZhbHVlLDEwKSxvPSQoIm91"
    "dCIpO28uY2xhc3NOYW1lPSJvdXQgb24iOwogaWYoaXNOYU4obil8fG48MCl7by50ZXh0Q29udGVudD0iVHlwZSBhbiBlbnRyeSBu"
    "dW1iZXIgKDAgb3IgbW9yZSkuIjtyZXR1cm59CiBvLnRleHRDb250ZW50PSJGZXRjaGluZyBlbnRyeSAiK24rIuKApiI7CiBmZXRj"
    "aCgiL3AvcmVjZWlwdD9sZWFmPSIrbix7Y2FjaGU6Im5vLXN0b3JlIn0pLnRoZW4oZnVuY3Rpb24ocil7cmV0dXJuIHIuanNvbigp"
    "fSkudGhlbihmdW5jdGlvbihkKXsKICBpZihkLmVycm9yKXtvLnRleHRDb250ZW50PSJObyBlbnRyeSAiK24rIiB5ZXQuIjtyZXR1"
    "cm59CiAgcmV0dXJuIHZlcmlmeShkLmVudHJ5X2hhc2gsZC5sZWFmX2luZGV4LGQudHJlZV9zaXplLGQuYXVkaXRfcGF0aCxkLnJv"
    "b3QpLnRoZW4oZnVuY3Rpb24ob2spewogICB2YXIgY3A9ZC5jaGVja3BvaW50OwogICBvLmlubmVySFRNTD0ob2s/JzxzcGFuIGNs"
    "YXNzPSJwYXNzIj5QQVNTPC9zcGFuPiBjaGVja2VkIGluIHlvdXIgYnJvd3NlcjogZW50cnkgJzonPHNwYW4gY2xhc3M9ImZhaWwi"
    "PkZBSUw8L3NwYW4+IHRoZSBtYXRocyBkb2VzIG5vdCBhZGQgdXAgZm9yIGVudHJ5ICcpK24rCiAgICIgaXMgaW4gdGhlIGxvZyBv"
    "ZiAiK2QudHJlZV9zaXplKyIgZW50cmllcy48YnI+RmluZ2VycHJpbnQ6ICIrZC5lbnRyeV9oYXNoKyI8YnI+Um9vdDogIitkLnJv"
    "b3QrCiAgIChjcCYmY3AuYmxvY2tfaW5kZXghPW51bGw/Jzxicj5TZWFsZWQgaW4gY2hhaW4gYmxvY2sgPGEgaHJlZj0iL3gvd2Fs"
    "ay9ibG9jaz9pbmRleD0nK2NwLmJsb2NrX2luZGV4KyciPicrY3AuYmxvY2tfaW5kZXgrIjwvYT4iOiI8YnI+U2VhbGluZyBpbnRv"
    "IHRoZSBjaGFpbiB3aXRoaW4gdGhlIG1pbnV0ZS4iKTsKICB9KTsKIH0pLmNhdGNoKGZ1bmN0aW9uKCl7by50ZXh0Q29udGVudD0i"
    "Q291bGRuJ3QgcmVhY2ggdGhlIGxvZy4ifSk7Cn0KJCgiZ28iKS5vbmNsaWNrPXJ1bjskKCJsZWFmIikuYWRkRXZlbnRMaXN0ZW5l"
    "cigia2V5ZG93biIsZnVuY3Rpb24oZSl7aWYoZS5rZXk9PT0iRW50ZXIiKXJ1bigpfSk7CmlmKGxvY2F0aW9uLmhhc2g9PT0iI2No"
    "ZWNrIikkKCJsZWFmIikuZm9jdXMoKTsKfSkoKTsKPC9zY3JpcHQ+PC9ib2R5PjwvaHRtbD4K"
)
_ADAPTER_B64 = (
    "IiIiCnNlYmJpX2FkYXB0ZXIucHkgIHYxLjEuMCAtIGRyb3AtaW4gc3RhdGUgYW5jaG9yaW5nIGZvciBsZWdhY3kgYXBwbGljYXRp"
    "b25zLgoKWW91ciBhcHBsaWNhdGlvbiBrZWVwcyBpdHMgZGF0YWJhc2UsIGl0cyBsb2dpYyBhbmQgaXRzIGluZnJhc3RydWN0dXJl"
    "LiBUaGlzCmZpbGUgc2l0cyBiZXNpZGUgaXQ6IGV2ZXJ5IHN0YXRlIGNoYW5nZSB5b3UgcG9pbnQgaXQgYXQgaXMgdHVybmVkIGlu"
    "dG8gYQpTSEEtMjU2IGZpbmdlcnByaW50LCBxdWV1ZWQgbG9jYWxseSwgYW5kIHNlbnQgaW4gdGhlIGJhY2tncm91bmQgdG8gdGhl"
    "CnNlYmJpLnBybyBwdWJsaWMgcHJvb2YgbG9nLCB3aGljaCByZXR1cm5zIGEgcmVjZWlwdCBwcm92aW5nIHRoZSBmaW5nZXJwcmlu"
    "dAppcyBpbiBhbiBhcHBlbmQtb25seSBSRkMgNjk2MiBNZXJrbGUgdHJlZSB3aG9zZSB0cmVlIGhlYWRzIGFyZSBzZWFsZWQgaW50"
    "byB0aGUKc2ViYmkucHJvIGNoYWluIGFuZCB0aW1lc3RhbXBlZCBpbiBCaXRjb2luLgoKT25seSB0aGUgZmluZ2VycHJpbnQgbGVh"
    "dmVzIHlvdXIgbWFjaGluZS4gVGhlIGRhdGEgaXRzZWxmIG5ldmVyIGRvZXMuCgpUV08gTElORVMKLS0tLS0tLS0tCiAgICBleHBv"
    "cnQgU0VCQklfQVBJX0tFWT15b3VyLWtleSAgICAgICAgICAob25jZSwgaW4gdGhlIGVudmlyb25tZW50KQoKICAgIGZyb20gc2Vi"
    "YmlfYWRhcHRlciBpbXBvcnQgYW5jaG9yX3N0YXRlCiAgICBAYW5jaG9yX3N0YXRlKCJvcmRlcnMudXBkYXRlIikKICAgIGRlZiB1"
    "cGRhdGVfb3JkZXIob3JkZXJfaWQsIHN0YXR1cyk6CiAgICAgICAgLi4uICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg"
    "IyB1bmNoYW5nZWQKICAgICAgICByZXR1cm4geyJvcmRlcl9pZCI6IG9yZGVyX2lkLCAic3RhdHVzIjogc3RhdHVzfQoKTmFtZSB0"
    "aGUgZGV2aWNlIGVhY2ggY2hhbmdlIGlzIGFib3V0IChhIHBob25lLCB0aWxsLCB0ZXJtaW5hbCwgY2FyKSBhbmQgaXQgaXMKbWV0"
    "ZXJlZCBwZXIgZGV2aWNlLCB0aGUgc2FtZSBhcyB0aGUgc2ViYmkucHJvIGVuZ2luZToKCiAgICBAYW5jaG9yX3N0YXRlKCJjYWxs"
    "cy5yb3V0ZSIsIGRldmljZT0iaGFuZHNldF9pZCIpICAgICMgYSBmaWVsZCBpbiB0aGUgcmVzdWx0CiAgICBAYW5jaG9yX3N0YXRl"
    "KCJwb3Muc2FsZSIsIGRldmljZT1sYW1iZGEgcmVzdWx0LCBhcmdzLCBrd2FyZ3M6IHJlc3VsdFsidGlsbCJdKQogICAgcmVjb3Jk"
    "KHsiYWNjb3VudCI6IDQyLCAiYmFsYW5jZSI6IDEyNTB9LCBkZXZpY2U9IklNRUktMzUuLi4iKQoKRGV2aWNlIG5hbWVzIGFyZSBv"
    "bmUtd2F5IGhhc2hlZCBvbiB5b3VyIG1hY2hpbmUgYmVmb3JlIHRoZXkgYXJlIHNlbnQuCgpUaGUgcmV0dXJuIHZhbHVlIGlzIGZp"
    "bmdlcnByaW50ZWQgYWZ0ZXIgdGhlIGZ1bmN0aW9uIHN1Y2NlZWRzLiBUaGUgY2FsbCBpcwpuZXZlciBzbG93ZWQgZG93biBieSB0"
    "aGUgbmV0d29yayBhbmQgbmV2ZXIgZmFpbHMgYmVjYXVzZSBvZiB0aGlzIGZpbGU6CmZpbmdlcnByaW50cyBnbyBpbnRvIGEgbG9j"
    "YWwgYXBwZW5kLW9ubHkgcXVldWUgKHNxbGl0ZSkgYW5kIGEgYmFja2dyb3VuZAp0aHJlYWQgc2VuZHMgdGhlbS4gSWYgc2ViYmku"
    "cHJvIGlzIHVucmVhY2hhYmxlIHRoZXkgd2FpdCwgYW5kIGFyZSBzZW50IHdoZW4gaXQKY29tZXMgYmFjaywgaW4gb3JkZXIsIHdp"
    "dGggbm8gZHVwbGljYXRlcy4KCk9USEVSIFdBWVMgSU4KLS0tLS0tLS0tLS0tLQogICAgZnJvbSBzZWJiaV9hZGFwdGVyIGltcG9y"
    "dCByZWNvcmQsIEFuY2hvckxvZ0hhbmRsZXIKICAgIHJlY29yZCh7ImFjY291bnQiOiA0MiwgImJhbGFuY2UiOiAxMjUwfSkgICAg"
    "ICAgICAgIyBhbnl3aGVyZSwgcmV0dXJucyB0aGUgaGFzaAogICAgbG9nZ2luZy5nZXRMb2dnZXIoInBheW1lbnRzIikuYWRkSGFu"
    "ZGxlcihBbmNob3JMb2dIYW5kbGVyKCkpICAgIyBldmVyeSBsb2cgbGluZQoKICAgIEBhbmNob3Jfc3RhdGUoImxlZGdlci5wb3N0"
    "IiwgY2FwdHVyZT0iYXJncyIpICAgICAgIyBmaW5nZXJwcmludCB0aGUgaW5wdXRzIGluc3RlYWQKICAgIEBhbmNob3Jfc3RhdGUo"
    "InVzZXIuc2F2ZSIsIGV4dHJhY3Q9bGFtYmRhIHJlc3VsdCwgYXJncywga3dhcmdzOiByZXN1bHQudG9fZGljdCgpKQoKQXN5bmMg"
    "ZnVuY3Rpb25zIHdvcmsgdGhlIHNhbWUgd2F5LgoKQ0hFQ0tJTkcKLS0tLS0tLS0KICAgIHB5dGhvbiBzZWJiaV9hZGFwdGVyLnB5"
    "IHN0YXR1cyAgICAgICAgICAgIHF1ZXVlIGFuZCByZWNlaXB0IGNvdW50cwogICAgcHl0aG9uIHNlYmJpX2FkYXB0ZXIucHkgZmx1"
    "c2ggICAgICAgICAgICAgc2VuZCB3aGF0IGlzIHdhaXRpbmcsIG5vdwogICAgcHl0aG9uIHNlYmJpX2FkYXB0ZXIucHkgcmVjZWlw"
    "dCA8aGFzaD4gICAgdGhlIHJlY2VpcHQgZm9yIG9uZSBmaW5nZXJwcmludAogICAgcHl0aG9uIHNlYmJpX2FkYXB0ZXIucHkgdmVy"
    "aWZ5ICAgICAgICAgICAgcmUtY2hlY2sgZXZlcnkgc3RvcmVkIHJlY2VpcHQgbG9jYWxseQogICAgcHl0aG9uIHNlYmJpX2FkYXB0"
    "ZXIucHkgaGFzaCAnPGpzb24+JyAgICAgZmluZ2VycHJpbnQgYSBKU09OIHZhbHVlIGV4YWN0bHkgYXMgdGhlIGFkYXB0ZXIgd291"
    "bGQKCkV2ZXJ5IHJlY2VpcHQgaXMgY2hlY2tlZCBvbiBhcnJpdmFsIHdpdGggYW4gUkZDIDY5NjIgaW5jbHVzaW9uIGNoZWNrLCBz"
    "byB0aGUKc2VydmVyJ3MgYW5zd2VyIGlzIHZlcmlmaWVkLCBub3QgdHJ1c3RlZC4gQSByZWNlaXB0IHRoYXQgZmFpbHMgdGhlIGNo"
    "ZWNrIGlzCmtlcHQgKGFzIGV2aWRlbmNlKSBhbmQgZmxhZ2dlZC4KCkZJTkdFUlBSSU5UIFJVTEUgKHNvIGFueW9uZSBjYW4gcmVj"
    "b21wdXRlIGl0KQotLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0KU0hBLTI1NiBvdmVyIGNhbm9u"
    "aWNhbCBKU09OOiBrZXlzIHNvcnRlZCwgc2VwYXJhdG9ycyAiLCIgYW5kICI6IiwgVVRGLTgsIG5vCmV4dHJhIHdoaXRlc3BhY2Uu"
    "IGRhdGV0aW1lL2RhdGUgLT4gSVNPIDg2MDEgc3RyaW5nLCBEZWNpbWFsIC0+IHN0cmluZywKYnl0ZXMgLT4gaGV4LCBzZXQgLT4g"
    "c29ydGVkIGxpc3QsIFVVSUQgLT4gc3RyaW5nLCBkYXRhY2xhc3MgLT4gaXRzIGZpZWxkcywKb2JqZWN0cyB3aXRoIHRvX2RpY3Qo"
    "KS9fYXNkaWN0KCkgLT4gdGhhdC4gRmxvYXRzIHVzZSBQeXRob24ncyByZXByLiBBbnl0aGluZwplbHNlIGlzIHJlZnVzZWQgKGFu"
    "ZCBsb2dnZWQpIHJhdGhlciB0aGFuIGd1ZXNzZWQgYXQgLSBwYXNzIGV4dHJhY3Q9IGZvciB0aG9zZS4KClBSSUNFCi0tLS0tCkZy"
    "ZWUgZm9yIDkwIGRheXMgb24gYSBuZXcgc2ViYmkucHJvIGtleSwgdGhlbiA1MHAgcGVyIGRldmljZSBwZXIgbW9udGg6CmV2ZXJ5"
    "IGRpc3RpbmN0IGRldmljZSB5b3VyIHJlY29yZHMgYXJlIGFib3V0LCBjb3VudGVkIG9uY2UgaW4gYSBjYWxlbmRhcgptb250aCBo"
    "b3dldmVyIG1hbnkgY2hhbmdlcyBpdCBtYWtlcy4gUmVjb3JkcyB3aXRoIG5vIGRldmljZSBuYW1lZCBjb3VudCB0aGUKbWFjaGlu"
    "ZSBydW5uaW5nIHRoaXMgZmlsZS4KClNFVFRJTkdTIChlbnZpcm9ubWVudCBvciBBbmNob3IoLi4uKSBhcmd1bWVudHMpCi0tLS0t"
    "LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tCiAgICBTRUJCSV9BUElfS0VZICAgICAgICB5b3VyIGtl"
    "eSAod2l0aG91dCBpdCwgZmluZ2VycHJpbnRzIHF1ZXVlIGFuZCB3YWl0KQogICAgU0VCQklfRU5EUE9JTlQgICAgICAgZGVmYXVs"
    "dCBodHRwczovL3NlYmJpLnBybwogICAgU0VCQklfREIgICAgICAgICAgICAgZGVmYXVsdCAuL3NlYmJpX2FuY2hvci5kYgogICAg"
    "U0VCQklfREVWSUNFX0lEICAgICAgbmFtZSB0aGlzIG1hY2hpbmUgeW91cnNlbGYgKGRlZmF1bHQ6IG1hZGUgb25jZSBhbmQga2Vw"
    "dCBpbiBTRUJCSV9EQikKICAgIFNFQkJJX0RJU0FCTEVEPTEgICAgIHJlY29yZCBub3RoaW5nIChraWxsIHN3aXRjaCkKClN0YW5k"
    "YXJkIGxpYnJhcnkgb25seS4gUHl0aG9uIDMuOCsuCiIiIgoKaW1wb3J0IGFzeW5jaW8KaW1wb3J0IGF0ZXhpdAppbXBvcnQgZGF0"
    "YWNsYXNzZXMKaW1wb3J0IGRhdGV0aW1lCmltcG9ydCBkZWNpbWFsCmltcG9ydCBmdW5jdG9vbHMKaW1wb3J0IGhhc2hsaWIKaW1w"
    "b3J0IGluc3BlY3QKaW1wb3J0IGpzb24KaW1wb3J0IGxvZ2dpbmcKaW1wb3J0IG9zCmltcG9ydCBzcWxpdGUzCmltcG9ydCBzeXMK"
    "aW1wb3J0IHRocmVhZGluZwppbXBvcnQgdGltZQppbXBvcnQgdXJsbGliLmVycm9yCmltcG9ydCB1cmxsaWIucmVxdWVzdAppbXBv"
    "cnQgdXVpZAoKX192ZXJzaW9uX18gPSAiMS4xLjAiCl9fYWxsX18gPSBbImFuY2hvcl9zdGF0ZSIsICJyZWNvcmQiLCAiQW5jaG9y"
    "IiwgIkFuY2hvckxvZ0hhbmRsZXIiLCAiY2Fub25pY2FsX2pzb24iLCAic3RhdGVfaGFzaCIsCiAgICAgICAgICAgInZlcmlmeV9p"
    "bmNsdXNpb24iLCAidmVyaWZ5X2NvbnNpc3RlbmN5IiwgImdldF9kZWZhdWx0Il0KCmxvZyA9IGxvZ2dpbmcuZ2V0TG9nZ2VyKCJz"
    "ZWJiaV9hZGFwdGVyIikKCgojIC0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t"
    "LS0tLS0tLS0gZmluZ2VycHJpbnRzCgpkZWYgX2RlZmF1bHQobyk6CiAgICBpZiBpc2luc3RhbmNlKG8sIChkYXRldGltZS5kYXRl"
    "dGltZSwgZGF0ZXRpbWUuZGF0ZSwgZGF0ZXRpbWUudGltZSkpOgogICAgICAgIHJldHVybiBvLmlzb2Zvcm1hdCgpCiAgICBpZiBp"
    "c2luc3RhbmNlKG8sIGRlY2ltYWwuRGVjaW1hbCk6CiAgICAgICAgcmV0dXJuIHN0cihvKQogICAgaWYgaXNpbnN0YW5jZShvLCAo"
    "Ynl0ZXMsIGJ5dGVhcnJheSwgbWVtb3J5dmlldykpOgogICAgICAgIHJldHVybiBieXRlcyhvKS5oZXgoKQogICAgaWYgaXNpbnN0"
    "YW5jZShvLCAoc2V0LCBmcm96ZW5zZXQpKToKICAgICAgICByZXR1cm4gc29ydGVkKG8sIGtleT1sYW1iZGEgeDogY2Fub25pY2Fs"
    "X2pzb24oeCkpCiAgICBpZiBpc2luc3RhbmNlKG8sIHV1aWQuVVVJRCk6CiAgICAgICAgcmV0dXJuIHN0cihvKQogICAgaWYgZGF0"
    "YWNsYXNzZXMuaXNfZGF0YWNsYXNzKG8pIGFuZCBub3QgaXNpbnN0YW5jZShvLCB0eXBlKToKICAgICAgICByZXR1cm4gZGF0YWNs"
    "YXNzZXMuYXNkaWN0KG8pCiAgICBmb3IgYXR0ciBpbiAoInRvX2RpY3QiLCAiX2FzZGljdCIpOgogICAgICAgIGZuID0gZ2V0YXR0"
    "cihvLCBhdHRyLCBOb25lKQogICAgICAgIGlmIGNhbGxhYmxlKGZuKToKICAgICAgICAgICAgcmV0dXJuIGZuKCkKICAgIHJhaXNl"
    "IFR5cGVFcnJvcigiY2Fubm90IGZpbmdlcnByaW50ICVzIC0gcGFzcyBleHRyYWN0PSB0byBjaG9vc2Ugd2hhdCB0byByZWNvcmQi"
    "ICUgdHlwZShvKS5fX25hbWVfXykKCgpkZWYgY2Fub25pY2FsX2pzb24ob2JqKToKICAgICIiIlRoZSBleGFjdCBieXRlcyB0aGUg"
    "ZmluZ2VycHJpbnQgaXMgdGFrZW4gb3Zlci4iIiIKICAgIHJldHVybiBqc29uLmR1bXBzKG9iaiwgc29ydF9rZXlzPVRydWUsIHNl"
    "cGFyYXRvcnM9KCIsIiwgIjoiKSwgZW5zdXJlX2FzY2lpPUZhbHNlLAogICAgICAgICAgICAgICAgICAgICAgYWxsb3dfbmFuPUZh"
    "bHNlLCBkZWZhdWx0PV9kZWZhdWx0KS5lbmNvZGUoInV0Zi04IikKCgpkZWYgc3RhdGVfaGFzaChvYmopOgogICAgIiIiU0hBLTI1"
    "NiBvZiBjYW5vbmljYWwgSlNPTiwgYXMgNjQgbG93ZXJjYXNlIGhleCBjaGFyYWN0ZXJzLiIiIgogICAgcmV0dXJuIGhhc2hsaWIu"
    "c2hhMjU2KGNhbm9uaWNhbF9qc29uKG9iaikpLmhleGRpZ2VzdCgpCgoKIyAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t"
    "LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tIFJGQyA2OTYyIGNoZWNrcwoKZGVmIF9oKGIpOgogICAgcmV0dXJuIGhh"
    "c2hsaWIuc2hhMjU2KGIpLmRpZ2VzdCgpCgoKZGVmIGxlYWZfaGFzaChlbnRyeV9oZXgpOgogICAgcmV0dXJuIF9oKGIiXHgwMCIg"
    "KyBieXRlcy5mcm9taGV4KGVudHJ5X2hleCkpLmhleCgpCgoKZGVmIHZlcmlmeV9pbmNsdXNpb24oZW50cnlfaGV4LCBpbmRleCwg"
    "dHJlZV9zaXplLCBwYXRoLCByb290KToKICAgICIiIlJGQyA5MTYyIHNlY3Rpb24gMi4xLjMuMjogaXMgZW50cnkgYXQgYGluZGV4"
    "YCBpbiB0aGUgdHJlZSBvZiBgdHJlZV9zaXplYCB3aXRoIGByb290YD8iIiIKICAgIHRyeToKICAgICAgICBpbmRleCwgdHJlZV9z"
    "aXplID0gaW50KGluZGV4KSwgaW50KHRyZWVfc2l6ZSkKICAgICAgICBpZiBpbmRleCA8IDAgb3IgaW5kZXggPj0gdHJlZV9zaXpl"
    "OgogICAgICAgICAgICByZXR1cm4gRmFsc2UKICAgICAgICBmbiwgc24gPSBpbmRleCwgdHJlZV9zaXplIC0gMQogICAgICAgIHIg"
    "PSBfaChiIlx4MDAiICsgYnl0ZXMuZnJvbWhleChlbnRyeV9oZXgpKQogICAgICAgIGZvciBwX2hleCBpbiBwYXRoOgogICAgICAg"
    "ICAgICBwID0gYnl0ZXMuZnJvbWhleChwX2hleCkKICAgICAgICAgICAgaWYgc24gPT0gMDoKICAgICAgICAgICAgICAgIHJldHVy"
    "biBGYWxzZQogICAgICAgICAgICBpZiAoZm4gJiAxKSBvciBmbiA9PSBzbjoKICAgICAgICAgICAgICAgIHIgPSBfaChiIlx4MDEi"
    "ICsgcCArIHIpCiAgICAgICAgICAgICAgICBpZiBub3QgKGZuICYgMSk6CiAgICAgICAgICAgICAgICAgICAgd2hpbGUgbm90IChm"
    "biAmIDEpIGFuZCBmbiAhPSAwOgogICAgICAgICAgICAgICAgICAgICAgICBmbiA+Pj0gMQogICAgICAgICAgICAgICAgICAgICAg"
    "ICBzbiA+Pj0gMQogICAgICAgICAgICBlbHNlOgogICAgICAgICAgICAgICAgciA9IF9oKGIiXHgwMSIgKyByICsgcCkKICAgICAg"
    "ICAgICAgZm4gPj49IDEKICAgICAgICAgICAgc24gPj49IDEKICAgICAgICByZXR1cm4gc24gPT0gMCBhbmQgciA9PSBieXRlcy5m"
    "cm9taGV4KHJvb3QpCiAgICBleGNlcHQgKFZhbHVlRXJyb3IsIFR5cGVFcnJvcik6CiAgICAgICAgcmV0dXJuIEZhbHNlCgoKZGVm"
    "IHZlcmlmeV9jb25zaXN0ZW5jeShmaXJzdCwgc2Vjb25kLCBmaXJzdF9yb290LCBzZWNvbmRfcm9vdCwgcHJvb2YpOgogICAgIiIi"
    "UkZDIDkxNjIgc2VjdGlvbiAyLjEuNC4yOiBpcyB0aGUgdHJlZSBvZiBzaXplIGBzZWNvbmRgIGFuIGFwcGVuZC1vbmx5IGV4dGVu"
    "c2lvbiBvZiBgZmlyc3RgPyIiIgogICAgdHJ5OgogICAgICAgIGZpcnN0LCBzZWNvbmQgPSBpbnQoZmlyc3QpLCBpbnQoc2Vjb25k"
    "KQogICAgICAgIGZyX2IsIHNyX2IgPSBieXRlcy5mcm9taGV4KGZpcnN0X3Jvb3QpLCBieXRlcy5mcm9taGV4KHNlY29uZF9yb290"
    "KQogICAgICAgIHBhdGggPSBbYnl0ZXMuZnJvbWhleChwKSBmb3IgcCBpbiBwcm9vZl0KICAgICAgICBpZiBmaXJzdCA9PSBzZWNv"
    "bmQ6CiAgICAgICAgICAgIHJldHVybiBub3QgcGF0aCBhbmQgZnJfYiA9PSBzcl9iCiAgICAgICAgaWYgZmlyc3QgPCAxIG9yIGZp"
    "cnN0ID4gc2Vjb25kIG9yIG5vdCBwYXRoOgogICAgICAgICAgICByZXR1cm4gRmFsc2UKICAgICAgICBpZiBmaXJzdCAmIChmaXJz"
    "dCAtIDEpID09IDA6CiAgICAgICAgICAgIHBhdGggPSBbZnJfYl0gKyBwYXRoCiAgICAgICAgZm4sIHNuID0gZmlyc3QgLSAxLCBz"
    "ZWNvbmQgLSAxCiAgICAgICAgd2hpbGUgZm4gJiAxOgogICAgICAgICAgICBmbiA+Pj0gMQogICAgICAgICAgICBzbiA+Pj0gMQog"
    "ICAgICAgIGZyID0gc3IgPSBwYXRoWzBdCiAgICAgICAgZm9yIGMgaW4gcGF0aFsxOl06CiAgICAgICAgICAgIGlmIHNuID09IDA6"
    "CiAgICAgICAgICAgICAgICByZXR1cm4gRmFsc2UKICAgICAgICAgICAgaWYgKGZuICYgMSkgb3IgZm4gPT0gc246CiAgICAgICAg"
    "ICAgICAgICBmciA9IF9oKGIiXHgwMSIgKyBjICsgZnIpCiAgICAgICAgICAgICAgICBzciA9IF9oKGIiXHgwMSIgKyBjICsgc3Ip"
    "CiAgICAgICAgICAgICAgICBpZiBub3QgKGZuICYgMSk6CiAgICAgICAgICAgICAgICAgICAgd2hpbGUgbm90IChmbiAmIDEpIGFu"
    "ZCBmbiAhPSAwOgogICAgICAgICAgICAgICAgICAgICAgICBmbiA+Pj0gMQogICAgICAgICAgICAgICAgICAgICAgICBzbiA+Pj0g"
    "MQogICAgICAgICAgICBlbHNlOgogICAgICAgICAgICAgICAgc3IgPSBfaChiIlx4MDEiICsgc3IgKyBjKQogICAgICAgICAgICBm"
    "biA+Pj0gMQogICAgICAgICAgICBzbiA+Pj0gMQogICAgICAgIHJldHVybiBmciA9PSBmcl9iIGFuZCBzciA9PSBzcl9iIGFuZCBz"
    "biA9PSAwCiAgICBleGNlcHQgKFZhbHVlRXJyb3IsIFR5cGVFcnJvcik6CiAgICAgICAgcmV0dXJuIEZhbHNlCgoKZGVmIGRldmlj"
    "ZV90b2tlbihkZXZpY2UpOgogICAgIiIiT25lLXdheSBkZXZpY2UgbmFtZSBzZW50IGZvciBtZXRlcmluZzogdGhlIHNhbWUgZGV2"
    "aWNlIGFsd2F5cyBnaXZlcyB0aGUgc2FtZSB0b2tlbi4iIiIKICAgIGlmIGRldmljZSBpcyBOb25lIG9yIGRldmljZSA9PSAiIjoK"
    "ICAgICAgICByZXR1cm4gTm9uZQogICAgcmV0dXJuICJkXyIgKyBoYXNobGliLnNoYTI1NigoInNlYmJpLWRldmljZToiICsgc3Ry"
    "KGRldmljZSkpLmVuY29kZSgidXRmLTgiKSkuaGV4ZGlnZXN0KClbOjMyXQoKCiMgLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t"
    "LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLSB0aGUgc2lkZWNhcgoKY2xhc3MgQW5jaG9yKG9iamVjdCk6CiAg"
    "ICAiIiJMb2NhbCBhcHBlbmQtb25seSBxdWV1ZSArIGJhY2tncm91bmQgc2VuZGVyLiBTYWZlIGFjcm9zcyB0aHJlYWRzLCBwcm9j"
    "ZXNzZXMgYW5kIGZvcmtzLiIiIgoKICAgIGRlZiBfX2luaXRfXyhzZWxmLCBhcGlfa2V5PU5vbmUsIGVuZHBvaW50PU5vbmUsIGRi"
    "X3BhdGg9Tm9uZSwgYmF0Y2hfc2l6ZT0yMDAsCiAgICAgICAgICAgICAgICAgZmx1c2hfaW50ZXJ2YWw9Mi4wLCB0aW1lb3V0PTEw"
    "LjAsIGNoZWNrX2NoYWluPVRydWUsIHN0YXJ0PVRydWUpOgogICAgICAgIHNlbGYuYXBpX2tleSA9IChhcGlfa2V5IGlmIGFwaV9r"
    "ZXkgaXMgbm90IE5vbmUgZWxzZSBvcy5lbnZpcm9uLmdldCgiU0VCQklfQVBJX0tFWSIsICIiKSkuc3RyaXAoKQogICAgICAgIHNl"
    "bGYuZW5kcG9pbnQgPSAoZW5kcG9pbnQgb3Igb3MuZW52aXJvbi5nZXQoIlNFQkJJX0VORFBPSU5UIiwgImh0dHBzOi8vc2ViYmku"
    "cHJvIikpLnJzdHJpcCgiLyIpCiAgICAgICAgc2VsZi5kYl9wYXRoID0gZGJfcGF0aCBvciBvcy5lbnZpcm9uLmdldCgiU0VCQklf"
    "REIiLCAic2ViYmlfYW5jaG9yLmRiIikKICAgICAgICBzZWxmLmJhdGNoX3NpemUgPSBtYXgoMSwgbWluKDUwMCwgaW50KGJhdGNo"
    "X3NpemUpKSkKICAgICAgICBzZWxmLmZsdXNoX2ludGVydmFsID0gZmxvYXQoZmx1c2hfaW50ZXJ2YWwpCiAgICAgICAgc2VsZi50"
    "aW1lb3V0ID0gZmxvYXQodGltZW91dCkKICAgICAgICBzZWxmLmNoZWNrX2NoYWluID0gYm9vbChjaGVja19jaGFpbikKICAgICAg"
    "ICBzZWxmLmRpc2FibGVkID0gb3MuZW52aXJvbi5nZXQoIlNFQkJJX0RJU0FCTEVEIiwgIjAiKSA9PSAiMSIKICAgICAgICBzZWxm"
    "Ll9hdXRvc3RhcnQgPSBzdGFydAogICAgICAgIHNlbGYuX3dhcm5lZF9ub19rZXkgPSBGYWxzZQogICAgICAgIGlmIG5vdCBzZWxm"
    "LmVuZHBvaW50LnN0YXJ0c3dpdGgoImh0dHBzOi8vIikgYW5kICIxMjcuMC4wLjEiIG5vdCBpbiBzZWxmLmVuZHBvaW50IFwKICAg"
    "ICAgICAgICAgICAgIGFuZCAibG9jYWxob3N0IiBub3QgaW4gc2VsZi5lbmRwb2ludDoKICAgICAgICAgICAgbG9nLndhcm5pbmco"
    "InNlYmJpX2FkYXB0ZXI6IGVuZHBvaW50ICVzIGlzIG5vdCBodHRwcyIsIHNlbGYuZW5kcG9pbnQpCiAgICAgICAgc2VsZi5faW5p"
    "dF9wcm9jZXNzKCkKCiAgICAjIC0tIHByb2Nlc3MtbG9jYWwgc3RhdGUgKHJlYnVpbHQgYWZ0ZXIgZm9yaykgLS0KICAgIGRlZiBf"
    "aW5pdF9wcm9jZXNzKHNlbGYpOgogICAgICAgIHNlbGYuX3BpZCA9IG9zLmdldHBpZCgpCiAgICAgICAgc2VsZi5fd2lkID0gIiVk"
    "LSVzIiAlIChzZWxmLl9waWQsIHV1aWQudXVpZDQoKS5oZXhbOjhdKQogICAgICAgIHNlbGYuX2xrID0gdGhyZWFkaW5nLkxvY2so"
    "KQogICAgICAgIHNlbGYuX3dha2UgPSB0aHJlYWRpbmcuRXZlbnQoKQogICAgICAgIHNlbGYuX3N0b3AgPSB0aHJlYWRpbmcuRXZl"
    "bnQoKQogICAgICAgIHNlbGYuX2JhY2tvZmYgPSAwLjAKICAgICAgICBzZWxmLl90cmllZCA9IHt9CiAgICAgICAgc2VsZi5fZGIg"
    "PSBzcWxpdGUzLmNvbm5lY3Qoc2VsZi5kYl9wYXRoLCB0aW1lb3V0PTMwLCBpc29sYXRpb25fbGV2ZWw9Tm9uZSwgY2hlY2tfc2Ft"
    "ZV90aHJlYWQ9RmFsc2UpCiAgICAgICAgc2VsZi5fZGIuZXhlY3V0ZSgiUFJBR01BIGpvdXJuYWxfbW9kZT1XQUwiKQogICAgICAg"
    "IHNlbGYuX2RiLmV4ZWN1dGUoIlBSQUdNQSBzeW5jaHJvbm91cz1OT1JNQUwiKQogICAgICAgIHNlbGYuX2RiLmV4ZWN1dGUoIkNS"
    "RUFURSBUQUJMRSBJRiBOT1QgRVhJU1RTIGVudHJpZXMoc2VxIElOVEVHRVIgUFJJTUFSWSBLRVkgQVVUT0lOQ1JFTUVOVCwiCiAg"
    "ICAgICAgICAgICAgICAgICAgICAgICAiY2lkIFRFWFQgVU5JUVVFIE5PVCBOVUxMLGhhc2ggVEVYVCBOT1QgTlVMTCxsYWJlbCBU"
    "RVhULGNyZWF0ZWQgUkVBTCkiKQogICAgICAgIHNlbGYuX2RiLmV4ZWN1dGUoIkNSRUFURSBUQUJMRSBJRiBOT1QgRVhJU1RTIHJl"
    "Y2VpcHRzKGlkIElOVEVHRVIgUFJJTUFSWSBLRVkgQVVUT0lOQ1JFTUVOVCwiCiAgICAgICAgICAgICAgICAgICAgICAgICAiY2lk"
    "IFRFWFQgTk9UIE5VTEwsbGVhZl9pbmRleCBJTlRFR0VSLHJlY2VpcHQgVEVYVCx2ZXJpZmllZCBJTlRFR0VSLCIKICAgICAgICAg"
    "ICAgICAgICAgICAgICAgICJjaGVja3BvaW50ZWQgSU5URUdFUiBERUZBVUxUIDAsaW5fY2hhaW4gSU5URUdFUixyZWNlaXZlZCBS"
    "RUFMKSIpCiAgICAgICAgc2VsZi5fZGIuZXhlY3V0ZSgiQ1JFQVRFIElOREVYIElGIE5PVCBFWElTVFMgcmVjZWlwdHNfY2lkIE9O"
    "IHJlY2VpcHRzKGNpZCkiKQogICAgICAgIHNlbGYuX2RiLmV4ZWN1dGUoIkNSRUFURSBJTkRFWCBJRiBOT1QgRVhJU1RTIGVudHJp"
    "ZXNfaGFzaCBPTiBlbnRyaWVzKGhhc2gpIikKICAgICAgICBzZWxmLl9kYi5leGVjdXRlKCJDUkVBVEUgVEFCTEUgSUYgTk9UIEVY"
    "SVNUUyBjbGFpbXMoY2lkIFRFWFQgUFJJTUFSWSBLRVksd29ya2VyIFRFWFQsdW50aWwgUkVBTCkiKQogICAgICAgIHNlbGYuX2Ri"
    "LmV4ZWN1dGUoIkNSRUFURSBUQUJMRSBJRiBOT1QgRVhJU1RTIG1ldGEoayBURVhUIFBSSU1BUlkgS0VZLHYgVEVYVCkiKQogICAg"
    "ICAgIHRyeToKICAgICAgICAgICAgc2VsZi5fZGIuZXhlY3V0ZSgiQUxURVIgVEFCTEUgZW50cmllcyBBREQgQ09MVU1OIGRldmlj"
    "ZSBURVhUIikKICAgICAgICBleGNlcHQgc3FsaXRlMy5PcGVyYXRpb25hbEVycm9yOgogICAgICAgICAgICBwYXNzCiAgICAgICAg"
    "c2VsZi5fZGIuZXhlY3V0ZSgiSU5TRVJUIE9SIElHTk9SRSBJTlRPIG1ldGEoayx2KSBWQUxVRVMoJ2RldmljZScsPykiLCAoImRl"
    "dl8iICsgdXVpZC51dWlkNCgpLmhleFs6MjBdLCkpCiAgICAgICAgc2VsZi5kZXZpY2UgPSAob3MuZW52aXJvbi5nZXQoIlNFQkJJ"
    "X0RFVklDRV9JRCIsICIiKS5zdHJpcCgpWzo2MF0gb3IKICAgICAgICAgICAgICAgICAgICAgICBzZWxmLl9kYi5leGVjdXRlKCJT"
    "RUxFQ1QgdiBGUk9NIG1ldGEgV0hFUkUgaz0nZGV2aWNlJyIpLmZldGNob25lKClbMF0pCiAgICAgICAgc2VsZi5fdGhyZWFkID0g"
    "Tm9uZQogICAgICAgIGlmIHNlbGYuX2F1dG9zdGFydDoKICAgICAgICAgICAgc2VsZi5fc3RhcnRfdGhyZWFkKCkKCiAgICBkZWYg"
    "X2Vuc3VyZV9wcm9jZXNzKHNlbGYpOgogICAgICAgIGlmIG9zLmdldHBpZCgpICE9IHNlbGYuX3BpZDoKICAgICAgICAgICAgc2Vs"
    "Zi5faW5pdF9wcm9jZXNzKCkKCiAgICBkZWYgX3N0YXJ0X3RocmVhZChzZWxmKToKICAgICAgICBpZiBzZWxmLl90aHJlYWQgYW5k"
    "IHNlbGYuX3RocmVhZC5pc19hbGl2ZSgpOgogICAgICAgICAgICByZXR1cm4KICAgICAgICBzZWxmLl90aHJlYWQgPSB0aHJlYWRp"
    "bmcuVGhyZWFkKHRhcmdldD1zZWxmLl9ydW4sIG5hbWU9InNlYmJpLWFuY2hvciIsIGRhZW1vbj1UcnVlKQogICAgICAgIHNlbGYu"
    "X3RocmVhZC5zdGFydCgpCgogICAgIyAtLSByZWNvcmRpbmcgKGhvc3Qgc2lkZTogbG9jYWwgb25seSwgbmV2ZXIgcmFpc2VzKSAt"
    "LQogICAgZGVmIHJlY29yZChzZWxmLCBwYXlsb2FkLCBsYWJlbD1Ob25lLCBkZXZpY2U9Tm9uZSk6CiAgICAgICAgIiIiRmluZ2Vy"
    "cHJpbnQgYHBheWxvYWRgIGFuZCBxdWV1ZSBpdC4gYGRldmljZWAgbmFtZXMgd2hhdCBpdCBpcyBhYm91dCAocGhvbmUsIHRpbGwu"
    "Li4pLgogICAgICAgIFJldHVybnMgdGhlIGhhc2gsIG9yIE5vbmUgaWYgaXQgY291bGQgbm90IGJlIHJlY29yZGVkLiIiIgogICAg"
    "ICAgIGlmIHNlbGYuZGlzYWJsZWQ6CiAgICAgICAgICAgIHJldHVybiBOb25lCiAgICAgICAgdHJ5OgogICAgICAgICAgICByZXR1"
    "cm4gc2VsZi5yZWNvcmRfaGFzaChzdGF0ZV9oYXNoKHBheWxvYWQpLCBsYWJlbD1sYWJlbCwgZGV2aWNlPWRldmljZSkKICAgICAg"
    "ICBleGNlcHQgRXhjZXB0aW9uIGFzIGU6CiAgICAgICAgICAgIGxvZy53YXJuaW5nKCJzZWJiaV9hZGFwdGVyOiBub3QgcmVjb3Jk"
    "ZWQgKCVzKSIsIGUpCiAgICAgICAgICAgIHJldHVybiBOb25lCgogICAgZGVmIHJlY29yZF9oYXNoKHNlbGYsIGhhc2hfaGV4LCBs"
    "YWJlbD1Ob25lLCBkZXZpY2U9Tm9uZSk6CiAgICAgICAgIiIiUXVldWUgYSBmaW5nZXJwcmludCB5b3UgY29tcHV0ZWQgeW91cnNl"
    "bGYgKDY0IGhleCBjaGFyYWN0ZXJzKS4iIiIKICAgICAgICBpZiBzZWxmLmRpc2FibGVkOgogICAgICAgICAgICByZXR1cm4gTm9u"
    "ZQogICAgICAgIHRyeToKICAgICAgICAgICAgaCA9IHN0cihoYXNoX2hleCkuc3RyaXAoKS5sb3dlcigpCiAgICAgICAgICAgIGlm"
    "IGxlbihoKSAhPSA2NCBvciBhbnkoY2ggbm90IGluICIwMTIzNDU2Nzg5YWJjZGVmIiBmb3IgY2ggaW4gaCk6CiAgICAgICAgICAg"
    "ICAgICByYWlzZSBWYWx1ZUVycm9yKCJoYXNoIG11c3QgYmUgNjQgaGV4IGNoYXJhY3RlcnMiKQogICAgICAgICAgICBzZWxmLl9l"
    "bnN1cmVfcHJvY2VzcygpCiAgICAgICAgICAgIHdpdGggc2VsZi5fbGs6CiAgICAgICAgICAgICAgICBzZWxmLl9kYi5leGVjdXRl"
    "KCJJTlNFUlQgSU5UTyBlbnRyaWVzKGNpZCxoYXNoLGxhYmVsLGNyZWF0ZWQsZGV2aWNlKSBWQUxVRVMoPyw/LD8sPyw/KSIsCiAg"
    "ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICh1dWlkLnV1aWQ0KCkuaGV4LCBoLCAoc3RyKGxhYmVsKVs6MTIwXSBpZiBs"
    "YWJlbCBlbHNlIE5vbmUpLCB0aW1lLnRpbWUoKSwKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIGRldmljZV90b2tl"
    "bihkZXZpY2UpKSkKICAgICAgICAgICAgc2VsZi5fd2FrZS5zZXQoKQogICAgICAgICAgICByZXR1cm4gaAogICAgICAgIGV4Y2Vw"
    "dCBFeGNlcHRpb24gYXMgZToKICAgICAgICAgICAgbG9nLndhcm5pbmcoInNlYmJpX2FkYXB0ZXI6IG5vdCByZWNvcmRlZCAoJXMp"
    "IiwgZSkKICAgICAgICAgICAgcmV0dXJuIE5vbmUKCiAgICAjIC0tIGxvb2t1cHMgLS0KICAgIGRlZiByZWNlaXB0KHNlbGYsIGhh"
    "c2hfaGV4KToKICAgICAgICAiIiJMYXRlc3QgcmVjZWlwdCBmb3IgYSBmaW5nZXJwcmludCAodGhlIG1vc3QgcmVjZW50IGVudHJ5"
    "IHdpdGggdGhhdCBoYXNoKSwgb3IgTm9uZS4iIiIKICAgICAgICBzZWxmLl9lbnN1cmVfcHJvY2VzcygpCiAgICAgICAgd2l0aCBz"
    "ZWxmLl9sazoKICAgICAgICAgICAgcm93ID0gc2VsZi5fZGIuZXhlY3V0ZSgKICAgICAgICAgICAgICAgICJTRUxFQ1Qgci5yZWNl"
    "aXB0LHIudmVyaWZpZWQsci5jaGVja3BvaW50ZWQsci5pbl9jaGFpbixlLmxhYmVsLGUuY3JlYXRlZCBGUk9NIGVudHJpZXMgZSAi"
    "CiAgICAgICAgICAgICAgICAiSk9JTiByZWNlaXB0cyByIE9OIHIuY2lkPWUuY2lkIFdIRVJFIGUuaGFzaD0/IE9SREVSIEJZIGUu"
    "c2VxIERFU0MsIHIuaWQgREVTQyBMSU1JVCAxIiwKICAgICAgICAgICAgICAgIChzdHIoaGFzaF9oZXgpLmxvd2VyKCksKSkuZmV0"
    "Y2hvbmUoKQogICAgICAgIGlmIG5vdCByb3c6CiAgICAgICAgICAgIHJldHVybiBOb25lCiAgICAgICAgcmVjID0ganNvbi5sb2Fk"
    "cyhyb3dbMF0pCiAgICAgICAgcmVjWyJ2ZXJpZmllZF9sb2NhbGx5Il0gPSBib29sKHJvd1sxXSkKICAgICAgICByZWNbImNoZWNr"
    "cG9pbnRlZCJdID0gYm9vbChyb3dbMl0pCiAgICAgICAgcmVjWyJ0cmVlX2hlYWRfc2Vlbl9pbl9jaGFpbiJdID0gTm9uZSBpZiBy"
    "b3dbM10gaXMgTm9uZSBlbHNlIGJvb2wocm93WzNdKQogICAgICAgIHJlY1sibGFiZWwiXSA9IHJvd1s0XQogICAgICAgIHJldHVy"
    "biByZWMKCiAgICBkZWYgY291bnRzKHNlbGYpOgogICAgICAgIHNlbGYuX2Vuc3VyZV9wcm9jZXNzKCkKICAgICAgICB3aXRoIHNl"
    "bGYuX2xrOgogICAgICAgICAgICBjID0gc2VsZi5fZGIKICAgICAgICAgICAgdG90YWwgPSBjLmV4ZWN1dGUoIlNFTEVDVCBDT1VO"
    "VCgqKSBGUk9NIGVudHJpZXMiKS5mZXRjaG9uZSgpWzBdCiAgICAgICAgICAgIHNlbnQgPSBjLmV4ZWN1dGUoIlNFTEVDVCBDT1VO"
    "VChESVNUSU5DVCBjaWQpIEZST00gcmVjZWlwdHMiKS5mZXRjaG9uZSgpWzBdCiAgICAgICAgICAgIGNwID0gYy5leGVjdXRlKCJT"
    "RUxFQ1QgQ09VTlQoRElTVElOQ1QgY2lkKSBGUk9NIHJlY2VpcHRzIFdIRVJFIGNoZWNrcG9pbnRlZD0xIikuZmV0Y2hvbmUoKVsw"
    "XQogICAgICAgICAgICBiYWQgPSBjLmV4ZWN1dGUoIlNFTEVDVCBDT1VOVChESVNUSU5DVCBjaWQpIEZST00gcmVjZWlwdHMgV0hF"
    "UkUgdmVyaWZpZWQ9MCIpLmZldGNob25lKClbMF0KICAgICAgICByZXR1cm4geyJyZWNvcmRlZCI6IHRvdGFsLCAicmVjZWlwdGVk"
    "Ijogc2VudCwgIndhaXRpbmciOiB0b3RhbCAtIHNlbnQsCiAgICAgICAgICAgICAgICAic2VhbGVkX2luX2NoYWluIjogY3AsICJm"
    "YWlsZWRfbG9jYWxfY2hlY2siOiBiYWR9CgogICAgZGVmIHBlbmRpbmcoc2VsZik6CiAgICAgICAgcmV0dXJuIHNlbGYuY291bnRz"
    "KClbIndhaXRpbmciXQoKICAgICMgLS0gbmV0d29yayAtLQogICAgZGVmIF9odHRwKHNlbGYsIG1ldGhvZCwgcGF0aCwgYm9keT1O"
    "b25lKToKICAgICAgICBkYXRhID0ganNvbi5kdW1wcyhib2R5KS5lbmNvZGUoInV0Zi04IikgaWYgYm9keSBpcyBub3QgTm9uZSBl"
    "bHNlIE5vbmUKICAgICAgICByZXEgPSB1cmxsaWIucmVxdWVzdC5SZXF1ZXN0KHNlbGYuZW5kcG9pbnQgKyBwYXRoLCBkYXRhPWRh"
    "dGEsIG1ldGhvZD1tZXRob2QpCiAgICAgICAgcmVxLmFkZF9oZWFkZXIoIkNvbnRlbnQtVHlwZSIsICJhcHBsaWNhdGlvbi9qc29u"
    "IikKICAgICAgICByZXEuYWRkX2hlYWRlcigiVXNlci1BZ2VudCIsICJzZWJiaS1hZGFwdGVyLyIgKyBfX3ZlcnNpb25fXykKICAg"
    "ICAgICBpZiBzZWxmLmFwaV9rZXk6CiAgICAgICAgICAgIHJlcS5hZGRfaGVhZGVyKCJYLVNlYmJpLUtleSIsIHNlbGYuYXBpX2tl"
    "eSkKICAgICAgICB0cnk6CiAgICAgICAgICAgIHdpdGggdXJsbGliLnJlcXVlc3QudXJsb3BlbihyZXEsIHRpbWVvdXQ9c2VsZi50"
    "aW1lb3V0KSBhcyByOgogICAgICAgICAgICAgICAgcmV0dXJuIHIuc3RhdHVzLCBqc29uLmxvYWRzKHIucmVhZCgpLmRlY29kZSgi"
    "dXRmLTgiKSBvciAie30iKQogICAgICAgIGV4Y2VwdCB1cmxsaWIuZXJyb3IuSFRUUEVycm9yIGFzIGU6CiAgICAgICAgICAgIHRy"
    "eToKICAgICAgICAgICAgICAgIHJldHVybiBlLmNvZGUsIGpzb24ubG9hZHMoZS5yZWFkKCkuZGVjb2RlKCJ1dGYtOCIpIG9yICJ7"
    "fSIpCiAgICAgICAgICAgIGV4Y2VwdCBFeGNlcHRpb246CiAgICAgICAgICAgICAgICByZXR1cm4gZS5jb2RlLCB7fQoKICAgIGRl"
    "ZiBfY2xhaW0oc2VsZiwgbik6CiAgICAgICAgbm93ID0gdGltZS50aW1lKCkKICAgICAgICB3aXRoIHNlbGYuX2xrOgogICAgICAg"
    "ICAgICBjID0gc2VsZi5fZGIKICAgICAgICAgICAgYy5leGVjdXRlKCJCRUdJTiBJTU1FRElBVEUiKQogICAgICAgICAgICB0cnk6"
    "CiAgICAgICAgICAgICAgICByb3dzID0gYy5leGVjdXRlKAogICAgICAgICAgICAgICAgICAgICJTRUxFQ1QgZS5jaWQsZS5oYXNo"
    "LGUuZGV2aWNlIEZST00gZW50cmllcyBlIFdIRVJFIE5PVCBFWElTVFMgKFNFTEVDVCAxIEZST00gcmVjZWlwdHMgciBXSEVSRSBy"
    "LmNpZD1lLmNpZCkgIgogICAgICAgICAgICAgICAgICAgICJBTkQgTk9UIEVYSVNUUyAoU0VMRUNUIDEgRlJPTSBjbGFpbXMgayBX"
    "SEVSRSBrLmNpZD1lLmNpZCBBTkQgay51bnRpbD4/IEFORCBrLndvcmtlcjw+PykgIgogICAgICAgICAgICAgICAgICAgICJPUkRF"
    "UiBCWSBlLnNlcSBMSU1JVCA/IiwgKG5vdywgc2VsZi5fd2lkLCBuKSkuZmV0Y2hhbGwoKQogICAgICAgICAgICAgICAgZm9yIGNp"
    "ZCwgXywgXyBpbiByb3dzOgogICAgICAgICAgICAgICAgICAgIGMuZXhlY3V0ZSgiSU5TRVJUIE9SIFJFUExBQ0UgSU5UTyBjbGFp"
    "bXMoY2lkLHdvcmtlcix1bnRpbCkgVkFMVUVTKD8sPyw/KSIsCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIChjaWQsIHNl"
    "bGYuX3dpZCwgbm93ICsgbWF4KDYwLjAsIHNlbGYudGltZW91dCAqIDMpKSkKICAgICAgICAgICAgICAgIGMuZXhlY3V0ZSgiQ09N"
    "TUlUIikKICAgICAgICAgICAgZXhjZXB0IEV4Y2VwdGlvbjoKICAgICAgICAgICAgICAgIGMuZXhlY3V0ZSgiUk9MTEJBQ0siKQog"
    "ICAgICAgICAgICAgICAgcmFpc2UKICAgICAgICByZXR1cm4gcm93cwoKICAgIGRlZiBfcmVsZWFzZShzZWxmLCBjaWRzKToKICAg"
    "ICAgICB3aXRoIHNlbGYuX2xrOgogICAgICAgICAgICBzZWxmLl9kYi5leGVjdXRlbWFueSgiREVMRVRFIEZST00gY2xhaW1zIFdI"
    "RVJFIGNpZD0/IEFORCB3b3JrZXI9PyIsIFsoYywgc2VsZi5fd2lkKSBmb3IgYyBpbiBjaWRzXSkKCiAgICBkZWYgX3N0b3JlKHNl"
    "bGYsIGNpZCwgcmVjLCBjaGVja3BvaW50ZWQ9RmFsc2UsIGluX2NoYWluPU5vbmUpOgogICAgICAgIG9rID0gdmVyaWZ5X2luY2x1"
    "c2lvbihyZWMuZ2V0KCJlbnRyeV9oYXNoIiwgIiIpLCByZWMuZ2V0KCJsZWFmX2luZGV4IiwgLTEpLCByZWMuZ2V0KCJ0cmVlX3Np"
    "emUiLCAwKSwKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgcmVjLmdldCgiYXVkaXRfcGF0aCIsIFtdKSwgcmVjLmdldCgi"
    "cm9vdCIsICIiKSkKICAgICAgICBpZiBjaGVja3BvaW50ZWQgYW5kIG9rIGFuZCByZWMuZ2V0KCJjaGVja3BvaW50Iik6CiAgICAg"
    "ICAgICAgIG9rID0gcmVjWyJjaGVja3BvaW50Il0uZ2V0KCJyb290IikgPT0gcmVjLmdldCgicm9vdCIpCiAgICAgICAgaWYgbm90"
    "IG9rOgogICAgICAgICAgICBsb2cuZXJyb3IoInNlYmJpX2FkYXB0ZXI6IHJlY2VpcHQgZm9yIGxlYWYgJXMgRkFJTEVEIHRoZSBs"
    "b2NhbCBpbmNsdXNpb24gY2hlY2sgLSBrZXB0IGFuZCBmbGFnZ2VkIiwKICAgICAgICAgICAgICAgICAgICAgIHJlYy5nZXQoImxl"
    "YWZfaW5kZXgiKSkKICAgICAgICB3aXRoIHNlbGYuX2xrOgogICAgICAgICAgICBzZWxmLl9kYi5leGVjdXRlKCJJTlNFUlQgSU5U"
    "TyByZWNlaXB0cyhjaWQsbGVhZl9pbmRleCxyZWNlaXB0LHZlcmlmaWVkLGNoZWNrcG9pbnRlZCxpbl9jaGFpbixyZWNlaXZlZCkg"
    "IgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICJWQUxVRVMoPyw/LD8sPyw/LD8sPykiLAogICAgICAgICAgICAgICAgICAg"
    "ICAgICAgICAgIChjaWQsIHJlYy5nZXQoImxlYWZfaW5kZXgiKSwganNvbi5kdW1wcyhyZWMsIHNvcnRfa2V5cz1UcnVlKSwgMSBp"
    "ZiBvayBlbHNlIDAsCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDEgaWYgY2hlY2twb2ludGVkIGVsc2UgMCwgaW5fY2hh"
    "aW4sIHRpbWUudGltZSgpKSkKICAgICAgICByZXR1cm4gb2sKCiAgICBkZWYgX3NlbmRfYmF0Y2goc2VsZik6CiAgICAgICAgIiIi"
    "U2VuZCBvbmUgYmF0Y2guIFJldHVybnMgbnVtYmVyIHJlY2VpcHRlZDsgcmFpc2VzIG9uIG5ldHdvcmsgZmFpbHVyZS4iIiIKICAg"
    "ICAgICBpZiBub3Qgc2VsZi5hcGlfa2V5OgogICAgICAgICAgICBpZiBub3Qgc2VsZi5fd2FybmVkX25vX2tleToKICAgICAgICAg"
    "ICAgICAgIGxvZy53YXJuaW5nKCJzZWJiaV9hZGFwdGVyOiBTRUJCSV9BUElfS0VZIG5vdCBzZXQgLSBmaW5nZXJwcmludHMgYXJl"
    "IHF1ZXVlZCBsb2NhbGx5IGFuZCB3aWxsICIKICAgICAgICAgICAgICAgICAgICAgICAgICAgICJiZSBzZW50IG9uY2UgaXQgaXMi"
    "KQogICAgICAgICAgICAgICAgc2VsZi5fd2FybmVkX25vX2tleSA9IFRydWUKICAgICAgICAgICAgcmV0dXJuIDAKICAgICAgICBy"
    "b3dzID0gc2VsZi5fY2xhaW0oc2VsZi5iYXRjaF9zaXplKQogICAgICAgIGlmIG5vdCByb3dzOgogICAgICAgICAgICByZXR1cm4g"
    "MAogICAgICAgIHdhbnRlZCA9IHtjaWQ6IGggZm9yIGNpZCwgaCwgXyBpbiByb3dzfQogICAgICAgIGl0ZW1zID0gW10KICAgICAg"
    "ICBmb3IgY2lkLCBoLCBkZXYgaW4gcm93czoKICAgICAgICAgICAgaXQgPSB7Imhhc2giOiBoLCAiY2lkIjogY2lkfQogICAgICAg"
    "ICAgICBpZiBkZXY6CiAgICAgICAgICAgICAgICBpdFsiZGV2aWNlIl0gPSBkZXYKICAgICAgICAgICAgaXRlbXMuYXBwZW5kKGl0"
    "KQogICAgICAgIHRyeToKICAgICAgICAgICAgY29kZSwgb3V0ID0gc2VsZi5faHR0cCgiUE9TVCIsICIvcC9zdWJtaXQiLCB7ImRl"
    "dmljZSI6IHNlbGYuZGV2aWNlLCAiaXRlbXMiOiBpdGVtc30pCiAgICAgICAgZXhjZXB0IEV4Y2VwdGlvbjoKICAgICAgICAgICAg"
    "c2VsZi5fcmVsZWFzZShsaXN0KHdhbnRlZCkpCiAgICAgICAgICAgIHJhaXNlCiAgICAgICAgaWYgY29kZSAhPSAyMDA6CiAgICAg"
    "ICAgICAgIHNlbGYuX3JlbGVhc2UobGlzdCh3YW50ZWQpKQogICAgICAgICAgICBpZiBjb2RlID09IDQwMjoKICAgICAgICAgICAg"
    "ICAgIGxvZy53YXJuaW5nKCJzZWJiaV9hZGFwdGVyOiB5b3VyIGZyZWUgdHJpYWwgaGFzIGVuZGVkIC0gZmluZ2VycHJpbnRzIGFy"
    "ZSBxdWV1ZWQgc2FmZWx5IGFuZCB3aWxsICIKICAgICAgICAgICAgICAgICAgICAgICAgICAgICJzZW5kIG9uY2UgdGhlIGtleSBp"
    "cyBwYWlkOiAlcyIsIG91dC5nZXQoImNoZWNrb3V0X3VybCIsICJodHRwczovL3NlYmJpLnByby9zdGFydCIpKQogICAgICAgICAg"
    "ICByYWlzZSBJT0Vycm9yKCJzZWJiaS5wcm8gYW5zd2VyZWQgJXM6ICVzIiAlIChjb2RlLCBvdXQuZ2V0KCJlcnJvciIpIG9yIG91"
    "dC5nZXQoIm1lc3NhZ2UiKSBvciAiIikpCiAgICAgICAgZG9uZSA9IDAKICAgICAgICBmb3IgcmVjIGluIG91dC5nZXQoInJlY2Vp"
    "cHRzIikgb3IgW106CiAgICAgICAgICAgIGNpZCA9IHJlYy5nZXQoImNpZCIpCiAgICAgICAgICAgIGlmIGNpZCBub3QgaW4gd2Fu"
    "dGVkOgogICAgICAgICAgICAgICAgY29udGludWUKICAgICAgICAgICAgaWYgcmVjLmdldCgiZXJyb3IiKToKICAgICAgICAgICAg"
    "ICAgIGxvZy5lcnJvcigic2ViYmlfYWRhcHRlcjogZW50cnkgJXMgcmVmdXNlZDogJXMiLCBjaWQsIHJlY1siZXJyb3IiXSkKICAg"
    "ICAgICAgICAgICAgIGNvbnRpbnVlCiAgICAgICAgICAgIGlmIHJlYy5nZXQoImVudHJ5X2hhc2giKSAhPSB3YW50ZWRbY2lkXToK"
    "ICAgICAgICAgICAgICAgIGxvZy5lcnJvcigic2ViYmlfYWRhcHRlcjogc2VydmVyIHJldHVybmVkIGEgZGlmZmVyZW50IGhhc2gg"
    "Zm9yICVzIC0gbm90IHN0b3JlZCIsIGNpZCkKICAgICAgICAgICAgICAgIGNvbnRpbnVlCiAgICAgICAgICAgIHNlbGYuX3N0b3Jl"
    "KGNpZCwgcmVjKQogICAgICAgICAgICBkb25lICs9IDEKICAgICAgICBzZWxmLl9yZWxlYXNlKGxpc3Qod2FudGVkKSkKICAgICAg"
    "ICByZXR1cm4gZG9uZQoKICAgIGRlZiBfdXBncmFkZShzZWxmLCBsaW1pdD01MCk6CiAgICAgICAgIiIiRmV0Y2ggc2VhbGVkIHJl"
    "Y2VpcHRzIGZvciBsZWF2ZXMgd2hvc2UgdHJlZSBoZWFkIHNob3VsZCBub3cgYmUgaW4gdGhlIGNoYWluLiIiIgogICAgICAgIGN1"
    "dG9mZiA9IHRpbWUudGltZSgpIC0gMzAKICAgICAgICB3aXRoIHNlbGYuX2xrOgogICAgICAgICAgICByb3dzID0gc2VsZi5fZGIu"
    "ZXhlY3V0ZSgKICAgICAgICAgICAgICAgICJTRUxFQ1Qgci5jaWQsci5sZWFmX2luZGV4IEZST00gcmVjZWlwdHMgciBXSEVSRSBy"
    "LnZlcmlmaWVkPTEgQU5EIHIucmVjZWl2ZWQ8PyBBTkQgIgogICAgICAgICAgICAgICAgIk5PVCBFWElTVFMgKFNFTEVDVCAxIEZS"
    "T00gcmVjZWlwdHMgcjIgV0hFUkUgcjIuY2lkPXIuY2lkIEFORCByMi5jaGVja3BvaW50ZWQ9MSkgIgogICAgICAgICAgICAgICAg"
    "IkdST1VQIEJZIHIuY2lkIE9SREVSIEJZIE1JTihyLmlkKSBMSU1JVCA/IiwgKGN1dG9mZiwgbGltaXQpKS5mZXRjaGFsbCgpCiAg"
    "ICAgICAgYmxvY2tzID0ge30KICAgICAgICBub3cgPSB0aW1lLnRpbWUoKQogICAgICAgIGZvciBjaWQsIGlkeCBpbiByb3dzOgog"
    "ICAgICAgICAgICBpZiBub3cgLSBzZWxmLl90cmllZC5nZXQoY2lkLCAwKSA8IDMwOgogICAgICAgICAgICAgICAgY29udGludWUK"
    "ICAgICAgICAgICAgc2VsZi5fdHJpZWRbY2lkXSA9IG5vdwogICAgICAgICAgICBjb2RlLCByZWMgPSBzZWxmLl9odHRwKCJHRVQi"
    "LCAiL3AvcmVjZWlwdD9sZWFmPSVkIiAlIGlkeCkKICAgICAgICAgICAgaWYgY29kZSAhPSAyMDAgb3Igbm90IHJlYy5nZXQoImNo"
    "ZWNrcG9pbnQiKToKICAgICAgICAgICAgICAgIGNvbnRpbnVlCiAgICAgICAgICAgIGluX2NoYWluID0gTm9uZQogICAgICAgICAg"
    "ICBpZiBzZWxmLmNoZWNrX2NoYWluOgogICAgICAgICAgICAgICAgYmxrID0gcmVjWyJjaGVja3BvaW50Il0uZ2V0KCJibG9ja19p"
    "bmRleCIpCiAgICAgICAgICAgICAgICBpZiBibGsgbm90IGluIGJsb2NrczoKICAgICAgICAgICAgICAgICAgICB0cnk6CiAgICAg"
    "ICAgICAgICAgICAgICAgICAgIF8sIGJvZHkgPSBzZWxmLl9odHRwKCJHRVQiLCAiL3gvd2Fsay9ibG9jaz9pbmRleD0lcyIgJSBi"
    "bGspCiAgICAgICAgICAgICAgICAgICAgICAgIGJsb2Nrc1tibGtdID0ganNvbi5kdW1wcyhib2R5KQogICAgICAgICAgICAgICAg"
    "ICAgIGV4Y2VwdCBFeGNlcHRpb246CiAgICAgICAgICAgICAgICAgICAgICAgIGJsb2Nrc1tibGtdID0gTm9uZQogICAgICAgICAg"
    "ICAgICAgaWYgYmxvY2tzW2Jsa10gaXMgbm90IE5vbmU6CiAgICAgICAgICAgICAgICAgICAgaW5fY2hhaW4gPSAxIGlmIHJlY1si"
    "Y2hlY2twb2ludCJdLmdldCgicm9vdCIsICJ+IikgaW4gYmxvY2tzW2Jsa10gZWxzZSAwCiAgICAgICAgICAgICAgICAgICAgaWYg"
    "bm90IGluX2NoYWluOgogICAgICAgICAgICAgICAgICAgICAgICBsb2cuZXJyb3IoInNlYmJpX2FkYXB0ZXI6IHRyZWUgaGVhZCBm"
    "b3IgbGVhZiAlcyBub3QgZm91bmQgaW4gY2hhaW4gYmxvY2sgJXMiLCBpZHgsIGJsaykKICAgICAgICAgICAgc2VsZi5fc3RvcmUo"
    "Y2lkLCByZWMsIGNoZWNrcG9pbnRlZD1UcnVlLCBpbl9jaGFpbj1pbl9jaGFpbikKICAgICAgICAgICAgc2VsZi5fdHJpZWQucG9w"
    "KGNpZCwgTm9uZSkKCiAgICBkZWYgZmx1c2goc2VsZiwgdGltZW91dD0zMC4wKToKICAgICAgICAiIiJTZW5kIGV2ZXJ5dGhpbmcg"
    "d2FpdGluZywgbm93LiBSZXR1cm5zIGhvdyBtYW55IHdlcmUgcmVjZWlwdGVkLiBOZXZlciByYWlzZXMuIiIiCiAgICAgICAgc2Vs"
    "Zi5fZW5zdXJlX3Byb2Nlc3MoKQogICAgICAgIGVuZCwgc2VudCA9IHRpbWUudGltZSgpICsgdGltZW91dCwgMAogICAgICAgIHdo"
    "aWxlIHRpbWUudGltZSgpIDwgZW5kOgogICAgICAgICAgICB0cnk6CiAgICAgICAgICAgICAgICBuID0gc2VsZi5fc2VuZF9iYXRj"
    "aCgpCiAgICAgICAgICAgIGV4Y2VwdCBFeGNlcHRpb24gYXMgZToKICAgICAgICAgICAgICAgIGxvZy53YXJuaW5nKCJzZWJiaV9h"
    "ZGFwdGVyOiBmbHVzaCBzdG9wcGVkICglcyk7IGVudHJpZXMgc3RheSBxdWV1ZWQiLCBlKQogICAgICAgICAgICAgICAgYnJlYWsK"
    "ICAgICAgICAgICAgc2VudCArPSBuCiAgICAgICAgICAgIGlmIG4gPT0gMDoKICAgICAgICAgICAgICAgIGJyZWFrCiAgICAgICAg"
    "cmV0dXJuIHNlbnQKCiAgICBkZWYgX3J1bihzZWxmKToKICAgICAgICB3aGlsZSBub3Qgc2VsZi5fc3RvcC5pc19zZXQoKToKICAg"
    "ICAgICAgICAgc2VsZi5fd2FrZS53YWl0KHNlbGYuX2JhY2tvZmYgb3Igc2VsZi5mbHVzaF9pbnRlcnZhbCkKICAgICAgICAgICAg"
    "c2VsZi5fd2FrZS5jbGVhcigpCiAgICAgICAgICAgIGlmIHNlbGYuX3N0b3AuaXNfc2V0KCk6CiAgICAgICAgICAgICAgICBicmVh"
    "awogICAgICAgICAgICB0cnk6CiAgICAgICAgICAgICAgICB3aGlsZSBzZWxmLl9zZW5kX2JhdGNoKCkgPj0gc2VsZi5iYXRjaF9z"
    "aXplOgogICAgICAgICAgICAgICAgICAgIHBhc3MKICAgICAgICAgICAgICAgIHNlbGYuX3VwZ3JhZGUoKQogICAgICAgICAgICAg"
    "ICAgc2VsZi5fYmFja29mZiA9IDAuMAogICAgICAgICAgICBleGNlcHQgRXhjZXB0aW9uIGFzIGU6CiAgICAgICAgICAgICAgICBz"
    "ZWxmLl9iYWNrb2ZmID0gbWluKDMwMC4wLCBtYXgoMi4wLCBzZWxmLl9iYWNrb2ZmICogMikpCiAgICAgICAgICAgICAgICBsb2cu"
    "aW5mbygic2ViYmlfYWRhcHRlcjogc2ViYmkucHJvIHVucmVhY2hhYmxlICglcyk7IHJldHJ5aW5nIGluICVkcyIsIGUsIHNlbGYu"
    "X2JhY2tvZmYpCgogICAgZGVmIGNsb3NlKHNlbGYsIGZsdXNoX3RpbWVvdXQ9Mi4wKToKICAgICAgICB0cnk6CiAgICAgICAgICAg"
    "IGlmIGZsdXNoX3RpbWVvdXQ6CiAgICAgICAgICAgICAgICBzZWxmLmZsdXNoKHRpbWVvdXQ9Zmx1c2hfdGltZW91dCkKICAgICAg"
    "ICBmaW5hbGx5OgogICAgICAgICAgICBzZWxmLl9zdG9wLnNldCgpCiAgICAgICAgICAgIHNlbGYuX3dha2Uuc2V0KCkKCgojIC0t"
    "LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0gdGhlIGRlZmF1bHQg"
    "aW5zdGFuY2UKCl9kZWZhdWx0X2FuY2hvciA9IE5vbmUKX2RlZmF1bHRfbG9jayA9IHRocmVhZGluZy5Mb2NrKCkKCgpkZWYgZ2V0"
    "X2RlZmF1bHQoKToKICAgIGdsb2JhbCBfZGVmYXVsdF9hbmNob3IKICAgIGlmIF9kZWZhdWx0X2FuY2hvciBpcyBOb25lOgogICAg"
    "ICAgIHdpdGggX2RlZmF1bHRfbG9jazoKICAgICAgICAgICAgaWYgX2RlZmF1bHRfYW5jaG9yIGlzIE5vbmU6CiAgICAgICAgICAg"
    "ICAgICBfZGVmYXVsdF9hbmNob3IgPSBBbmNob3IoKQogICAgICAgICAgICAgICAgYXRleGl0LnJlZ2lzdGVyKF9kZWZhdWx0X2Fu"
    "Y2hvci5jbG9zZSkKICAgIHJldHVybiBfZGVmYXVsdF9hbmNob3IKCgpkZWYgcmVjb3JkKHBheWxvYWQsIGxhYmVsPU5vbmUsIGFu"
    "Y2hvcj1Ob25lLCBkZXZpY2U9Tm9uZSk6CiAgICAiIiJGaW5nZXJwcmludCBhbmQgcXVldWUgYW55IEpTT04tYWJsZSB2YWx1ZS4g"
    "UmV0dXJucyB0aGUgaGFzaC4gTmV2ZXIgcmFpc2VzLiIiIgogICAgdHJ5OgogICAgICAgIHJldHVybiAoYW5jaG9yIG9yIGdldF9k"
    "ZWZhdWx0KCkpLnJlY29yZChwYXlsb2FkLCBsYWJlbD1sYWJlbCwgZGV2aWNlPWRldmljZSkKICAgIGV4Y2VwdCBFeGNlcHRpb24g"
    "YXMgZToKICAgICAgICBsb2cud2FybmluZygic2ViYmlfYWRhcHRlcjogbm90IHJlY29yZGVkICglcykiLCBlKQogICAgICAgIHJl"
    "dHVybiBOb25lCgoKZGVmIGFuY2hvcl9zdGF0ZShsYWJlbD1Ob25lLCBjYXB0dXJlPSJyZXN1bHQiLCBleHRyYWN0PU5vbmUsIGFu"
    "Y2hvcj1Ob25lLCBkZXZpY2U9Tm9uZSk6CiAgICAiIiJEZWNvcmF0b3IuIEFmdGVyIHRoZSB3cmFwcGVkIGZ1bmN0aW9uIHN1Y2Nl"
    "ZWRzLCBmaW5nZXJwcmludCBpdHMgc3RhdGUgYW5kIHF1ZXVlIGl0LgoKICAgIGNhcHR1cmU6ICAicmVzdWx0IiAoZGVmYXVsdCkg"
    "LSB0aGUgcmV0dXJuIHZhbHVlCiAgICAgICAgICAgICAgImFyZ3MiICAgICAgICAgICAgIC0gdGhlIGFyZ3VtZW50cyBpdCB3YXMg"
    "Y2FsbGVkIHdpdGgKICAgICAgICAgICAgICAiYm90aCIgICAgICAgICAgICAgLSB7ImFyZ3MiOiAuLi4sICJrd2FyZ3MiOiAuLi4s"
    "ICJyZXN1bHQiOiAuLi59CiAgICBleHRyYWN0OiAgZihyZXN1bHQsIGFyZ3MsIGt3YXJncykgLT4gdGhlIHZhbHVlIHRvIGZpbmdl"
    "cnByaW50IChvdmVycmlkZXMgY2FwdHVyZSkKICAgIGRldmljZTogICB3aGF0IHRoZSBjaGFuZ2UgaXMgYWJvdXQsIGZvciB0aGUg"
    "cGVyLWRldmljZSBtZXRlcjogYSBmaWVsZCBuYW1lIGluIHRoZSByZXN1bHQKICAgICAgICAgICAgICAob3IgYSBrZXl3b3JkIGFy"
    "Z3VtZW50KSwgb3IgZihyZXN1bHQsIGFyZ3MsIGt3YXJncykgLT4gZGV2aWNlIG5hbWUKICAgIFRoZSB3cmFwcGVkIGZ1bmN0aW9u"
    "J3MgYmVoYXZpb3VyLCByZXR1cm4gdmFsdWUgYW5kIGV4Y2VwdGlvbnMgYXJlIHVuY2hhbmdlZC4KICAgICIiIgogICAgaWYgY2Fs"
    "bGFibGUobGFiZWwpIGFuZCBub3QgaXNpbnN0YW5jZShsYWJlbCwgc3RyKToKICAgICAgICByZXR1cm4gYW5jaG9yX3N0YXRlKCko"
    "bGFiZWwpCgogICAgZGVmIGRlY28oZm4pOgogICAgICAgIG5hbWUgPSBsYWJlbCBvciBnZXRhdHRyKGZuLCAiX19xdWFsbmFtZV9f"
    "IiwgZ2V0YXR0cihmbiwgIl9fbmFtZV9fIiwgImNhbGwiKSkKCiAgICAgICAgZGVmIF9zdGF0ZShhcmdzLCBrd2FyZ3MsIHJlc3Vs"
    "dCk6CiAgICAgICAgICAgIGlmIGV4dHJhY3QgaXMgbm90IE5vbmU6CiAgICAgICAgICAgICAgICByZXR1cm4gZXh0cmFjdChyZXN1"
    "bHQsIGFyZ3MsIGt3YXJncykKICAgICAgICAgICAgaWYgY2FwdHVyZSA9PSAiYXJncyI6CiAgICAgICAgICAgICAgICByZXR1cm4g"
    "eyJhcmdzIjogbGlzdChhcmdzKSwgImt3YXJncyI6IGt3YXJnc30KICAgICAgICAgICAgaWYgY2FwdHVyZSA9PSAiYm90aCI6CiAg"
    "ICAgICAgICAgICAgICByZXR1cm4geyJhcmdzIjogbGlzdChhcmdzKSwgImt3YXJncyI6IGt3YXJncywgInJlc3VsdCI6IHJlc3Vs"
    "dH0KICAgICAgICAgICAgcmV0dXJuIHJlc3VsdAoKICAgICAgICBkZWYgX2RldmljZShhcmdzLCBrd2FyZ3MsIHJlc3VsdCk6CiAg"
    "ICAgICAgICAgIGlmIGRldmljZSBpcyBOb25lOgogICAgICAgICAgICAgICAgcmV0dXJuIE5vbmUKICAgICAgICAgICAgaWYgY2Fs"
    "bGFibGUoZGV2aWNlKToKICAgICAgICAgICAgICAgIHJldHVybiBkZXZpY2UocmVzdWx0LCBhcmdzLCBrd2FyZ3MpCiAgICAgICAg"
    "ICAgIGlmIGlzaW5zdGFuY2UocmVzdWx0LCBkaWN0KSBhbmQgZGV2aWNlIGluIHJlc3VsdDoKICAgICAgICAgICAgICAgIHJldHVy"
    "biByZXN1bHRbZGV2aWNlXQogICAgICAgICAgICBpZiBkZXZpY2UgaW4ga3dhcmdzOgogICAgICAgICAgICAgICAgcmV0dXJuIGt3"
    "YXJnc1tkZXZpY2VdCiAgICAgICAgICAgIHJldHVybiBnZXRhdHRyKHJlc3VsdCwgZGV2aWNlLCBOb25lKQoKICAgICAgICBkZWYg"
    "X2FuY2hvcihhcmdzLCBrd2FyZ3MsIHJlc3VsdCk6CiAgICAgICAgICAgIHRyeToKICAgICAgICAgICAgICAgIHRyeToKICAgICAg"
    "ICAgICAgICAgICAgICBkZXYgPSBfZGV2aWNlKGFyZ3MsIGt3YXJncywgcmVzdWx0KQogICAgICAgICAgICAgICAgZXhjZXB0IEV4"
    "Y2VwdGlvbjoKICAgICAgICAgICAgICAgICAgICBkZXYgPSBOb25lCiAgICAgICAgICAgICAgICByZWNvcmQoX3N0YXRlKGFyZ3Ms"
    "IGt3YXJncywgcmVzdWx0KSwgbGFiZWw9bmFtZSwgYW5jaG9yPWFuY2hvciwgZGV2aWNlPWRldikKICAgICAgICAgICAgZXhjZXB0"
    "IEV4Y2VwdGlvbiBhcyBlOgogICAgICAgICAgICAgICAgbG9nLndhcm5pbmcoInNlYmJpX2FkYXB0ZXI6ICVzIG5vdCByZWNvcmRl"
    "ZCAoJXMpIiwgbmFtZSwgZSkKCiAgICAgICAgaWYgaW5zcGVjdC5pc2Nvcm91dGluZWZ1bmN0aW9uKGZuKToKICAgICAgICAgICAg"
    "QGZ1bmN0b29scy53cmFwcyhmbikKICAgICAgICAgICAgYXN5bmMgZGVmIGF3cmFwcGVyKCphcmdzLCAqKmt3YXJncyk6CiAgICAg"
    "ICAgICAgICAgICByZXN1bHQgPSBhd2FpdCBmbigqYXJncywgKiprd2FyZ3MpCiAgICAgICAgICAgICAgICBfYW5jaG9yKGFyZ3Ms"
    "IGt3YXJncywgcmVzdWx0KQogICAgICAgICAgICAgICAgcmV0dXJuIHJlc3VsdAogICAgICAgICAgICByZXR1cm4gYXdyYXBwZXIK"
    "CiAgICAgICAgQGZ1bmN0b29scy53cmFwcyhmbikKICAgICAgICBkZWYgd3JhcHBlcigqYXJncywgKiprd2FyZ3MpOgogICAgICAg"
    "ICAgICByZXN1bHQgPSBmbigqYXJncywgKiprd2FyZ3MpCiAgICAgICAgICAgIF9hbmNob3IoYXJncywga3dhcmdzLCByZXN1bHQp"
    "CiAgICAgICAgICAgIHJldHVybiByZXN1bHQKICAgICAgICByZXR1cm4gd3JhcHBlcgogICAgcmV0dXJuIGRlY28KCgpjbGFzcyBB"
    "bmNob3JMb2dIYW5kbGVyKGxvZ2dpbmcuSGFuZGxlcik6CiAgICAiIiJGaW5nZXJwcmludHMgZXZlcnkgbG9nIHJlY29yZCBpdCBz"
    "ZWVzOiBsb2dnZXIsIGxldmVsLCBtZXNzYWdlIGFuZCB0aW1lLiIiIgoKICAgIGRlZiBfX2luaXRfXyhzZWxmLCBhbmNob3I9Tm9u"
    "ZSwgbGV2ZWw9bG9nZ2luZy5JTkZPKToKICAgICAgICBsb2dnaW5nLkhhbmRsZXIuX19pbml0X18oc2VsZiwgbGV2ZWwpCiAgICAg"
    "ICAgc2VsZi5fYW5jaG9yID0gYW5jaG9yCgogICAgZGVmIGVtaXQoc2VsZiwgcmVjKToKICAgICAgICBpZiByZWMubmFtZS5zdGFy"
    "dHN3aXRoKCJzZWJiaV9hZGFwdGVyIik6CiAgICAgICAgICAgIHJldHVybgogICAgICAgIHRyeToKICAgICAgICAgICAgcmVjb3Jk"
    "KHsibG9nZ2VyIjogcmVjLm5hbWUsICJsZXZlbCI6IHJlYy5sZXZlbG5hbWUsICJtZXNzYWdlIjogcmVjLmdldE1lc3NhZ2UoKSwK"
    "ICAgICAgICAgICAgICAgICAgICAidGltZSI6IHJvdW5kKHJlYy5jcmVhdGVkLCA2KX0sIGxhYmVsPSJsb2c6IiArIHJlYy5uYW1l"
    "LCBhbmNob3I9c2VsZi5fYW5jaG9yKQogICAgICAgIGV4Y2VwdCBFeGNlcHRpb246CiAgICAgICAgICAgIHBhc3MKCgojIC0tLS0t"
    "LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0gY29tbWFuZCBsaW5lCgpk"
    "ZWYgX21haW4oYXJndik6CiAgICBsb2dnaW5nLmJhc2ljQ29uZmlnKGxldmVsPWxvZ2dpbmcuSU5GTywgZm9ybWF0PSIlKG1lc3Nh"
    "Z2UpcyIpCiAgICBjbWQgPSBhcmd2WzFdIGlmIGxlbihhcmd2KSA+IDEgZWxzZSAic3RhdHVzIgogICAgaWYgY21kID09ICJoYXNo"
    "IiBhbmQgbGVuKGFyZ3YpID4gMjoKICAgICAgICBwcmludChzdGF0ZV9oYXNoKGpzb24ubG9hZHMoYXJndlsyXSkpKQogICAgICAg"
    "IHJldHVybiAwCiAgICBhID0gQW5jaG9yKHN0YXJ0PUZhbHNlKQogICAgaWYgY21kID09ICJzdGF0dXMiOgogICAgICAgIHByaW50"
    "KGpzb24uZHVtcHMoZGljdChhLmNvdW50cygpLCBlbmRwb2ludD1hLmVuZHBvaW50LCBkYj1hLmRiX3BhdGgsIGRldmljZT1hLmRl"
    "dmljZSwKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAga2V5X3NldD1ib29sKGEuYXBpX2tleSkpLCBpbmRlbnQ9MikpCiAg"
    "ICBlbGlmIGNtZCA9PSAiZmx1c2giOgogICAgICAgIHByaW50KCJyZWNlaXB0ZWQgJWQiICUgYS5mbHVzaCh0aW1lb3V0PTEyMCkp"
    "CiAgICAgICAgYS5fdXBncmFkZShsaW1pdD01MDApCiAgICAgICAgcHJpbnQoanNvbi5kdW1wcyhhLmNvdW50cygpLCBpbmRlbnQ9"
    "MikpCiAgICBlbGlmIGNtZCA9PSAicmVjZWlwdCIgYW5kIGxlbihhcmd2KSA+IDI6CiAgICAgICAgcHJpbnQoanNvbi5kdW1wcyhh"
    "LnJlY2VpcHQoYXJndlsyXSksIGluZGVudD0yKSkKICAgIGVsaWYgY21kID09ICJ2ZXJpZnkiOgogICAgICAgIHdpdGggYS5fbGs6"
    "CiAgICAgICAgICAgIHJvd3MgPSBhLl9kYi5leGVjdXRlKCJTRUxFQ1QgcmVjZWlwdCBGUk9NIHJlY2VpcHRzIikuZmV0Y2hhbGwo"
    "KQogICAgICAgIGdvb2QgPSBzdW0oMSBmb3IgKHIsKSBpbiByb3dzIGlmIChsYW1iZGEgZDogdmVyaWZ5X2luY2x1c2lvbihkLmdl"
    "dCgiZW50cnlfaGFzaCIsICIiKSwgZC5nZXQoImxlYWZfaW5kZXgiLCAtMSksCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAg"
    "ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICBkLmdldCgidHJlZV9zaXplIiwgMCksIGQuZ2V0KCJhdWRp"
    "dF9wYXRoIiwgW10pLAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg"
    "ICAgICAgICAgZC5nZXQoInJvb3QiLCAiIikpKShqc29uLmxvYWRzKHIpKSkKICAgICAgICBwcmludCgiJWQgb2YgJWQgc3RvcmVk"
    "IHJlY2VpcHRzIHBhc3MgdGhlIFJGQyA2OTYyIGluY2x1c2lvbiBjaGVjayIgJSAoZ29vZCwgbGVuKHJvd3MpKSkKICAgIGVsc2U6"
    "CiAgICAgICAgcHJpbnQoX19kb2NfXykKICAgIHJldHVybiAwCgoKaWYgX19uYW1lX18gPT0gIl9fbWFpbl9fIjoKICAgIHN5cy5l"
    "eGl0KF9tYWluKHN5cy5hcmd2KSkK"
)
_EXAMPLE_B64 = (
    "IiIiCmV4YW1wbGVfbGVnYWN5X2FwcC5weSAtIGhvdyBhbiBleGlzdGluZyBhcHBsaWNhdGlvbiBwbHVncyBpbiBzZWJiaV9hZGFw"
    "dGVyLgoKTm90aGluZyBpbiB0aGUgYnVzaW5lc3MgbG9naWMgY2hhbmdlcy4gRWFjaCBleGFtcGxlIGlzIHRoZSBvcmlnaW5hbCBj"
    "b2RlIHBsdXMKdGhlIGFkYXB0ZXIgbGluZXMgbWFya2VkICAjIDwtIHNlYmJpLgoKUnVuIGl0OiAgIFNFQkJJX0FQSV9LRVk9eW91"
    "ci1rZXkgcHl0aG9uIGV4YW1wbGVfbGVnYWN5X2FwcC5weQpUaGVuOiAgICAgcHl0aG9uIHNlYmJpX2FkYXB0ZXIucHkgc3RhdHVz"
    "CiIiIgoKaW1wb3J0IGFzeW5jaW8KaW1wb3J0IGxvZ2dpbmcKaW1wb3J0IHNxbGl0ZTMKCmZyb20gc2ViYmlfYWRhcHRlciBpbXBv"
    "cnQgYW5jaG9yX3N0YXRlLCByZWNvcmQsIEFuY2hvckxvZ0hhbmRsZXIgICAjIDwtIHNlYmJpIChsaW5lIDEpCgoKIyAtLS0tIDEu"
    "IEEgZGF0YWJhc2Ugd3JpdGUuIFR3byBsaW5lczogdGhlIGltcG9ydCBhYm92ZSBhbmQgdGhlIGRlY29yYXRvci4gLS0tLQoKZGIg"
    "PSBzcWxpdGUzLmNvbm5lY3QoIjptZW1vcnk6IikKZGIuZXhlY3V0ZSgiQ1JFQVRFIFRBQkxFIGFjY291bnRzKGlkIElOVEVHRVIg"
    "UFJJTUFSWSBLRVksIGJhbGFuY2UgSU5URUdFUikiKQpkYi5leGVjdXRlKCJJTlNFUlQgSU5UTyBhY2NvdW50cyBWQUxVRVMoNDIs"
    "IDEwMDApIikKCgpAYW5jaG9yX3N0YXRlKCJhY2NvdW50cy5kZWJpdCIpICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg"
    "ICAgIyA8LSBzZWJiaSAobGluZSAyKQpkZWYgZGViaXQoYWNjb3VudF9pZCwgYW1vdW50KToKICAgIGRiLmV4ZWN1dGUoIlVQREFU"
    "RSBhY2NvdW50cyBTRVQgYmFsYW5jZSA9IGJhbGFuY2UgLSA/IFdIRVJFIGlkID0gPyIsIChhbW91bnQsIGFjY291bnRfaWQpKQog"
    "ICAgZGIuY29tbWl0KCkKICAgIGJhbGFuY2UgPSBkYi5leGVjdXRlKCJTRUxFQ1QgYmFsYW5jZSBGUk9NIGFjY291bnRzIFdIRVJF"
    "IGlkID0gPyIsIChhY2NvdW50X2lkLCkpLmZldGNob25lKClbMF0KICAgIHJldHVybiB7ImFjY291bnQiOiBhY2NvdW50X2lkLCAi"
    "ZGViaXRlZCI6IGFtb3VudCwgImJhbGFuY2UiOiBiYWxhbmNlfQoKCiMgLS0tLSAyLiBBbiBBUEkgaGFuZGxlciwgbWV0ZXJlZCBw"
    "ZXIgZGV2aWNlOiBuYW1lIHRoZSBoYW5kc2V0IGVhY2ggY2hhbmdlIGlzIGFib3V0LiAtLS0tCgpAYW5jaG9yX3N0YXRlKCJvcmRl"
    "cnMucGxhY2UiLCBjYXB0dXJlPSJib3RoIiwgZGV2aWNlPSJoYW5kc2V0IikgICAjIDUwcCBwZXIgaGFuZHNldCBwZXIgbW9udGgK"
    "ZGVmIHBsYWNlX29yZGVyKGN1c3RvbWVyLCBpdGVtcywgaGFuZHNldCk6CiAgICByZXR1cm4geyJvcmRlcl9pZCI6IDcwMDEsICJj"
    "dXN0b21lciI6IGN1c3RvbWVyLCAiaXRlbXMiOiBpdGVtcywgInN0YXR1cyI6ICJhY2NlcHRlZCJ9CgoKIyAtLS0tIDMuIEFuIGFz"
    "eW5jIGhhbmRsZXIuIFNhbWUgZGVjb3JhdG9yLiAtLS0tCgpAYW5jaG9yX3N0YXRlKCJwYXltZW50cy5yZWZ1bmQiKQphc3luYyBk"
    "ZWYgcmVmdW5kKHBheW1lbnRfaWQpOgogICAgYXdhaXQgYXN5bmNpby5zbGVlcCgwKQogICAgcmV0dXJuIHsicGF5bWVudCI6IHBh"
    "eW1lbnRfaWQsICJzdGF0dXMiOiAicmVmdW5kZWQifQoKCiMgLS0tLSA0LiBBIHZhbHVlIHlvdSBvbmx5IHdhbnQgcGFydCBvZjog"
    "Y2hvb3NlIGl0IHdpdGggZXh0cmFjdD0uIC0tLS0KCmNsYXNzIFVzZXIob2JqZWN0KToKICAgIGRlZiBfX2luaXRfXyhzZWxmLCB1"
    "aWQsIGVtYWlsLCByb2xlKToKICAgICAgICBzZWxmLnVpZCwgc2VsZi5lbWFpbCwgc2VsZi5yb2xlID0gdWlkLCBlbWFpbCwgcm9s"
    "ZQoKCkBhbmNob3Jfc3RhdGUoInVzZXJzLnNldF9yb2xlIiwgZXh0cmFjdD1sYW1iZGEgcmVzdWx0LCBhcmdzLCBrd2FyZ3M6IHsi"
    "dWlkIjogcmVzdWx0LnVpZCwgInJvbGUiOiByZXN1bHQucm9sZX0pCmRlZiBzZXRfcm9sZSh1c2VyLCByb2xlKToKICAgIHVzZXIu"
    "cm9sZSA9IHJvbGUKICAgIHJldHVybiB1c2VyCgoKIyAtLS0tIDUuIEFuIGV4aXN0aW5nIGxvZ2dlcjogZXZlcnkgSU5GTyBsaW5l"
    "IGFuZCBhYm92ZSBpcyBmaW5nZXJwcmludGVkLiAtLS0tCgphdWRpdCA9IGxvZ2dpbmcuZ2V0TG9nZ2VyKCJhdWRpdCIpCmF1ZGl0"
    "LnNldExldmVsKGxvZ2dpbmcuSU5GTykKYXVkaXQuYWRkSGFuZGxlcihBbmNob3JMb2dIYW5kbGVyKCkpICAgICAgICAgICAgICAg"
    "ICAgICAgICAgICAgICAgICMgPC0gc2ViYmkKCgppZiBfX25hbWVfXyA9PSAiX19tYWluX18iOgogICAgZGViaXQoNDIsIDI1MCkK"
    "ICAgIHBsYWNlX29yZGVyKCJhY21lIiwgWyJ3aWRnZXQiLCAiZ2VhciJdLCBoYW5kc2V0PSJJTUVJLTM1NjkzODAzNTY0MzgwOSIp"
    "CiAgICBhc3luY2lvLnJ1bihyZWZ1bmQoInBheV84ODEiKSkKICAgIHNldF9yb2xlKFVzZXIoNSwgImFAZXhhbXBsZS5jb20iLCAi"
    "dmlld2VyIiksICJhZG1pbiIpCiAgICBhdWRpdC5pbmZvKCJtb250aC1lbmQgY2xvc2UgY29tcGxldGVkIikKICAgIGggPSByZWNv"
    "cmQoeyJiYXRjaCI6ICIyMDI2LTA5IiwgInJvd3MiOiAxMjA0fSkgICAgICAgICAgICAgICAgIyBhIG9uZS1vZmYsIGFueXdoZXJl"
    "CiAgICByZWNvcmQoeyJ0aWxsIjogNCwgInNhbGUiOiAxMi41MH0sIGRldmljZT0idGlsbC00IikgICAgICAgICAgICMgYSBvbmUt"
    "b2ZmIGFib3V0IGEgZGV2aWNlCiAgICBwcmludCgicmVjb3JkZWQsIGZpbmdlcnByaW50IG9mIHRoZSBiYXRjaDoiLCBoKQogICAg"
    "cHJpbnQoInJlY2VpcHRzIGFycml2ZSBpbiB0aGUgYmFja2dyb3VuZDsgY2hlY2sgd2l0aDogIHB5dGhvbiBzZWJiaV9hZGFwdGVy"
    "LnB5IHN0YXR1cyIpCg=="
)


def _d(b):
    return base64.b64decode("".join(b.split()))


_FILES = {
    "/plugin": (_d(_PAGE_B64), "text/html; charset=utf-8", None),
    "/p/sebbi_adapter.py": (_d(_ADAPTER_B64), "text/x-python; charset=utf-8", "sebbi_adapter.py"),
    "/p/example_legacy_app.py": (_d(_EXAMPLE_B64), "text/x-python; charset=utf-8", "example_legacy_app.py"),
}

_ctx = {}
_ready = False
_patched = False
_loaded = False
_leaves = []            # leaf hashes (bytes), index = leaf index
_cache = {}             # (start, size) -> hash, for complete power-of-two subtrees
_tree_lock = threading.Lock()
_cp_lock = threading.Lock()
_loop_started = False


# ---------------------------------------------------------------- RFC 6962

def _h(b):
    return hashlib.sha256(b).digest()


def _leaf_hash(entry):
    return _h(b"\x00" + entry)


def _node(left, right):
    return _h(b"\x01" + left + right)


def _split(n):
    """Largest power of two strictly less than n (n >= 2)."""
    k = 1
    while k * 2 < n:
        k *= 2
    return k


def _mth(start, n):
    """Merkle Tree Hash of leaves[start:start+n]."""
    if n == 0:
        return _h(b"")
    if n == 1:
        return _leaves[start]
    full = n >= 16 and (n & (n - 1)) == 0
    if full:
        hit = _cache.get((start, n))
        if hit is not None:
            return hit
    k = _split(n)
    out = _node(_mth(start, k), _mth(start + k, n - k))
    if full:
        _cache[(start, n)] = out
    return out


def _path(m, start, n):
    """Audit path for leaf m within leaves[start:start+n]."""
    if n <= 1:
        return []
    k = _split(n)
    if m < k:
        return _path(m, start, k) + [_mth(start + k, n - k)]
    return _path(m - k, start + k, n - k) + [_mth(start, k)]


def _subproof(m, start, n, b):
    if m == n:
        return [] if b else [_mth(start, n)]
    k = _split(n)
    if m <= k:
        return _subproof(m, start, k, b) + [_mth(start + k, n - k)]
    return _subproof(m - k, start + k, n - k, False) + [_mth(start, k)]


def _consistency(m, n):
    if m <= 0 or m >= n:
        return []
    return _subproof(m, 0, n, True)


# ---------------------------------------------------------------- storage

def _setup():
    global _ready
    if _ready or "conn" not in _ctx:
        return
    with _ctx["lock"]:
        c = _ctx["conn"]
        c.execute("CREATE TABLE IF NOT EXISTS ppa_leaf(idx INTEGER PRIMARY KEY,entry_hash TEXT NOT NULL,"
                  "leaf_hash TEXT NOT NULL,client TEXT,cid TEXT,ts REAL,UNIQUE(client,cid))")
        c.execute("CREATE INDEX IF NOT EXISTS ppa_leaf_entry ON ppa_leaf(entry_hash)")
        c.execute("CREATE TABLE IF NOT EXISTS ppa_sth(tree_size INTEGER PRIMARY KEY,root TEXT NOT NULL,"
                  "ts REAL,audit_hash TEXT,block_index INTEGER)")
        c.commit()
    _ready = True


def _reload_locked(c):
    """Rebuild the in-memory tree from the database. Caller holds _ctx['lock']."""
    rows = c.execute("SELECT idx,leaf_hash FROM ppa_leaf ORDER BY idx").fetchall()
    fresh = []
    for i, (idx, lh) in enumerate(rows):
        if idx != i:
            raise RuntimeError("leaf index gap at %d" % i)
        fresh.append(bytes.fromhex(lh))
    _cache.clear()
    _leaves[:] = fresh


def _load():
    global _loaded
    if _loaded:
        return
    with _tree_lock:
        if _loaded:
            return
        with _ctx["lock"]:
            _reload_locked(_ctx["conn"])
        _loaded = True


def _seal(kind, detail, extra):
    ev = {"user_id": "ppa:" + kind[:20], "action": kind, "amount": 0, "country": "UK",
          "device_id": "public-proof-adapter", "anomaly": 0, "device_risk": 0}
    res = {"decision": kind.upper(), "score": 0, "adapter_version": VERSION, "detail": detail}
    res.update(extra or {})
    out = _ctx["seal"](ev, res, time.time(), KEY)
    if isinstance(out, (list, tuple)):
        return out[0], (out[1] if len(out) > 1 else None)
    return out, None


def _sth_rows(sql, args=()):
    with _ctx["lock"]:
        return _ctx["conn"].execute(sql, args).fetchall()


def _latest_sth():
    r = _sth_rows("SELECT tree_size,root,ts,audit_hash,block_index FROM ppa_sth ORDER BY tree_size DESC LIMIT 1")
    return _sth_dict(r[0]) if r else None


def _covering_sth(idx):
    r = _sth_rows("SELECT tree_size,root,ts,audit_hash,block_index FROM ppa_sth WHERE tree_size>? "
                  "ORDER BY tree_size ASC LIMIT 1", (idx,))
    return _sth_dict(r[0]) if r else None


def _sth_dict(r):
    return {"tree_size": r[0], "root": r[1],
            "sealed_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime(r[2] or 0)),
            "audit_hash": r[3], "block_index": r[4],
            "walk": SITE + "/x/walk/block?index=%s" % r[4] if r[4] is not None else None,
            "ts": r[2] or 0}


# ---------------------------------------------------------------- appends and checkpoints

def _append(client, items):
    """items: list of (entry_hex, cid or None). Returns list of (idx, entry_hex, replayed, error)."""
    for attempt in range(3):
        out = []
        with _ctx["lock"]:
            c = _ctx["conn"]
            top = c.execute("SELECT COALESCE(MAX(idx),-1) FROM ppa_leaf").fetchone()[0]
            if top + 1 != len(_leaves):
                _reload_locked(c)
            start_len = len(_leaves)
            try:
                for eh, cid in items:
                    if cid:
                        row = c.execute("SELECT idx,entry_hash FROM ppa_leaf WHERE client=? AND cid=?",
                                        (client, cid)).fetchone()
                        if row:
                            if row[1] != eh:
                                out.append((None, eh, False, "cid_reused_for_a_different_hash"))
                            else:
                                out.append((row[0], eh, True, None))
                            continue
                    idx = len(_leaves)
                    lh = _leaf_hash(bytes.fromhex(eh))
                    c.execute("INSERT INTO ppa_leaf(idx,entry_hash,leaf_hash,client,cid,ts) VALUES(?,?,?,?,?,?)",
                              (idx, eh, lh.hex(), client, cid or None, time.time()))
                    _leaves.append(lh)
                    out.append((idx, eh, False, None))
                c.commit()
                return out
            except sqlite3.IntegrityError:
                c.rollback()
                del _leaves[start_len:]
                _reload_locked(c)
            except Exception:
                c.rollback()
                del _leaves[start_len:]
                raise
    raise RuntimeError("could not append after retries")


def _checkpoint(force=False):
    """Seal the current tree head into the chain if it is due. Never runs twice at once."""
    if "conn" not in _ctx or not _cp_lock.acquire(blocking=False):
        return None
    try:
        _load()
        n = len(_leaves)
        last = _latest_sth()
        last_size = last["tree_size"] if last else 0
        if n == 0 or n == last_size:
            return last
        due = force or (n - last_size) >= CHECKPOINT_EVERY or \
            (time.time() - (last["ts"] if last else 0)) >= CHECKPOINT_SECONDS
        if not due:
            return last
        root = _mth(0, n).hex()
        ah, blk = _seal("tree_head", "size=%d;root=%s" % (n, root),
                        {"tree_size": n, "root": root, "prev_tree_size": last_size,
                         "log": "sebbi public proof log", "spec": "RFC6962-SHA256"})
        with _ctx["lock"]:
            _ctx["conn"].execute("INSERT OR IGNORE INTO ppa_sth(tree_size,root,ts,audit_hash,block_index) "
                                 "VALUES(?,?,?,?,?)", (n, root, time.time(), ah, blk))
            _ctx["conn"].commit()
        return _latest_sth()
    finally:
        _cp_lock.release()


def _loop():
    while True:
        time.sleep(10)
        try:
            _checkpoint()
        except Exception as e:
            print("public_proof_adapter checkpoint: " + str(e)[:160], flush=True)


def _start_loop():
    global _loop_started
    if _loop_started:
        return
    _loop_started = True
    threading.Thread(target=_loop, name="ppa-checkpoint", daemon=True).start()


# ---------------------------------------------------------------- receipts

def _anchoring_note(cp):
    if not cp:
        return ("pending: this leaf is covered by the next tree head, sealed into the chain within about "
                "%d seconds. Fetch /p/receipt?leaf=N again after that." % CHECKPOINT_SECONDS)
    return ("tree head sealed in chain block %s. The chain tip is timestamped in Bitcoin via OpenTimestamps; "
            "once a confirmed anchored tip is at or after that block, this leaf is Bitcoin-anchored. "
            "Check: %s/x/ots/latest_confirmed" % (cp["block_index"], SITE))


def _receipt(idx, size=None):
    _load()
    n = len(_leaves)
    if idx < 0 or idx >= n:
        return None
    with _ctx["lock"]:
        row = _ctx["conn"].execute("SELECT entry_hash FROM ppa_leaf WHERE idx=?", (idx,)).fetchone()
    cp = _covering_sth(idx) if size is None else None
    tsize = size if size is not None else (cp["tree_size"] if cp else n)
    tsize = max(idx + 1, min(tsize, n))
    root = _mth(0, tsize).hex()
    rec = {"log": "sebbi.pro public proof log", "spec": SPEC,
           "entry_hash": row[0] if row else None, "leaf_index": idx,
           "leaf_hash": _leaves[idx].hex(), "tree_size": tsize, "root": root,
           "audit_path": [p.hex() for p in _path(idx, 0, tsize)],
           "checkpoint": None, "anchoring": _anchoring_note(cp)}
    if cp:
        c2 = dict(cp)
        c2.pop("ts", None)
        c2["root_matches"] = (cp["root"] == root)
        rec["checkpoint"] = c2
    return rec


# ---------------------------------------------------------------- commands

def _meter(key, devices):
    """Count each distinct device on the key's monthly meter - the engine's own record_device()."""
    key = str(key or "").strip()
    devices = [d for d in dict.fromkeys(devices) if d and CID_RE.match(d)]
    if not key or not devices:
        return None
    rd = _server_fn("record_device")
    n = None
    for d in devices:
        dev_id = "adapter:" + d
        if rd:
            try:
                n = rd(key, dev_id)
                continue
            except Exception:
                pass
        try:
            with _ctx["lock"]:
                c = _ctx["conn"]
                c.execute("INSERT OR IGNORE INTO device_seen(api_key,device_id,first_seen) VALUES(?,?,?)",
                          (key, dev_id, time.time()))
                c.commit()
                n = c.execute("SELECT COUNT(*) FROM device_seen WHERE api_key=?", (key,)).fetchone()[0]
        except Exception:
            try:
                _ctx["conn"].rollback()
            except Exception:
                pass
    return n


TRIAL_DAYS = 90


def _server_fn(name):
    """Borrow a function from the running server (server.py) if it is there."""
    for modname in ("__main__", "server"):
        m = sys.modules.get(modname)
        fn = getattr(m, name, None) if m else None
        if callable(fn):
            return fn
    return None


def _trial_gate(key):
    """None if the key may submit; otherwise the same 402 answer the engine gives at trial end."""
    try:
        with _ctx["lock"]:
            row = _ctx["conn"].execute("SELECT email,is_paid,created,product FROM api_keys WHERE key=?",
                                       (key,)).fetchone()
    except Exception:
        return None
    if not row:
        return None
    email, is_paid, created, product = row
    ts = _server_fn("trial_state")
    in_trial = ts(created, is_paid)[0] if ts else (bool(is_paid) or time.time() - (created or 0) <= TRIAL_DAYS * 86400)
    if in_trial:
        return None
    dc = _server_fn("device_count")
    tc = _server_fn("trial_checkout")
    try:
        devices = dc(key) if dc else None
    except Exception:
        devices = None
    try:
        url = tc(key, email, product or "aileash") if tc else SITE + "/#signup"
    except Exception:
        url = SITE + "/#signup"
    return {"error": "trial_expired",
            "message": "Your 90-day free trial has ended. Your receipts, proofs and queued fingerprints are "
                       "untouched - pay to continue exactly where you left off. The bill is 50p for each real "
                       "device that used your key.",
            "billable_devices": devices, "rate_per_device_gbp": 0.50, "checkout_url": url}


def _client_for(key):
    key = str(key or "").strip()
    if key:
        try:
            with _ctx["lock"]:
                row = _ctx["conn"].execute("SELECT active FROM api_keys WHERE key=?", (key,)).fetchone()
        except Exception:
            row = None
        if row and row[0] in (1, None):
            return "k_" + hashlib.sha256(key.encode("utf-8")).hexdigest()[:16]
    return "open" if OPEN else None


def c_submit(q, body, key):
    client = _client_for(key)
    if not client:
        return {"error": "api_key_required",
                "message": "Send your sebbi.pro API key in the X-Sebbi-Key header."}, 401
    if client != "open":
        gate = _trial_gate(str(key).strip())
        if gate:
            return gate, 402
    raw = body.get("items")
    if raw is None and body.get("hashes") is not None:
        raw = [{"hash": h} for h in body.get("hashes") or []]
    if raw is None and body.get("hash") is not None:
        raw = [{"hash": body.get("hash"), "cid": body.get("cid")}]
    if not isinstance(raw, list) or not raw:
        return {"error": "nothing_to_submit", "message": 'Send {"items":[{"hash":"<64 hex>","cid":"..."}]}'}, 400
    if len(raw) > MAX_ITEMS:
        return {"error": "too_many", "max_items": MAX_ITEMS}, 413
    items, bad, devs = [], [], []
    install = str(body.get("device") or "").strip()
    for i, it in enumerate(raw):
        it = it if isinstance(it, dict) else {"hash": it}
        h = str(it.get("hash") or "").strip().lower()
        cid = str(it.get("cid") or "").strip() or None
        dev = str(it.get("device") or "").strip() or install
        if not HEX64.match(h):
            bad.append({"position": i, "error": "hash must be 64 hex characters (SHA-256)"})
        elif cid and not CID_RE.match(cid):
            bad.append({"position": i, "error": "cid must be 1-80 letters, numbers, _ . : -"})
        elif dev and not CID_RE.match(dev):
            bad.append({"position": i, "error": "device must be 1-80 letters, numbers, _ . : -"})
        else:
            items.append((h, cid))
            devs.append(dev)
    if bad:
        return {"error": "bad_items", "items": bad}, 400
    _load()
    devices = _meter(key, devs) if client != "open" else None
    placed = _append(client, items)
    n = len(_leaves)
    last = _latest_sth()
    if n - (last["tree_size"] if last else 0) >= CHECKPOINT_EVERY:
        threading.Thread(target=_checkpoint, daemon=True).start()
    receipts = []
    for (idx, eh, replayed, err), (_, cid) in zip(placed, items):
        if err:
            receipts.append({"cid": cid, "entry_hash": eh, "error": err})
            continue
        r = _receipt(idx, size=n)
        r["cid"] = cid
        r["replayed"] = replayed
        r["anchoring"] = _anchoring_note(None)
        receipts.append(r)
    return {"accepted": sum(1 for r in receipts if "error" not in r), "tree_size": n,
            "devices_this_month": devices,
            "root": _mth(0, n).hex(), "receipts": receipts}, 200


def _int(q, name, default=None):
    try:
        return int(str(q.get(name, default)))
    except (TypeError, ValueError):
        return None


def c_receipt(q, body, key):
    idx = _int(q, "leaf")
    if idx is None:
        return {"error": "leaf needed"}, 400
    r = _receipt(idx)
    return (r, 200) if r else ({"error": "no such leaf"}, 404)


def c_proof(q, body, key):
    idx, size = _int(q, "leaf"), _int(q, "size", 0)
    if idx is None:
        return {"error": "leaf needed"}, 400
    r = _receipt(idx, size=size or len(_leaves))
    return (r, 200) if r else ({"error": "no such leaf"}, 404)


def c_consistency(q, body, key):
    _load()
    m, n = _int(q, "first"), _int(q, "second", len(_leaves))
    if m is None or n is None or m < 1 or m > n or n > len(_leaves):
        return {"error": "need 1 <= first <= second <= tree size", "tree_size": len(_leaves)}, 400
    return {"first": m, "second": n, "first_root": _mth(0, m).hex(), "second_root": _mth(0, n).hex(),
            "proof": [p.hex() for p in _consistency(m, n)], "spec": SPEC}, 200


def c_sth(q, body, key):
    _load()
    last = _latest_sth()
    if last:
        last.pop("ts", None)
    return {"tree_size": len(_leaves), "latest_sealed_tree_head": last,
            "checkpoint_every_seconds": CHECKPOINT_SECONDS, "spec": SPEC}, 200


def c_find(q, body, key):
    h = str(q.get("hash") or "").strip().lower()
    if not HEX64.match(h):
        return {"error": "hash must be 64 hex characters"}, 400
    rows = _sth_rows("SELECT idx FROM ppa_leaf WHERE entry_hash=? ORDER BY idx LIMIT 50", (h,))
    return {"entry_hash": h, "leaf_indexes": [r[0] for r in rows]}, 200


def c_index(q, body, key):
    return {"log": "sebbi.pro public proof log", "version": VERSION, "spec": SPEC,
            "submit": "POST " + SITE + "/p/submit with X-Sebbi-Key",
            "check": ["GET " + SITE + "/p/receipt?leaf=N", "GET " + SITE + "/p/consistency?first=M&second=N",
                      "GET " + SITE + "/p/sth"],
            "hash_only": True}, 200


GETS = {"receipt": c_receipt, "proof": c_proof, "consistency": c_consistency, "sth": c_sth,
        "find": c_find, "": c_index}
POSTS = {"submit": c_submit}


# ---------------------------------------------------------------- transport

def _send(h, obj, code=200):
    body = json.dumps(obj).encode("utf-8")
    h.send_response(code)
    h.send_header("Content-Type", "application/json; charset=utf-8")
    h.send_header("Content-Length", str(len(body)))
    h.send_header("Access-Control-Allow-Origin", "*")
    h.send_header("Access-Control-Allow-Headers", "Content-Type, X-Sebbi-Key")
    h.send_header("Access-Control-Allow-Methods", "GET, POST, OPTIONS")
    h.send_header("Cache-Control", "no-store")
    h.end_headers()
    h.wfile.write(body)


def _run(h, method):
    u = urllib.parse.urlparse(h.path)
    name = u.path[3:].strip("/").lower()
    table = GETS if method == "GET" else POSTS
    if name not in table:
        return False
    if "conn" not in _ctx:
        _send(h, {"error": "not_armed", "message": "open /x/public_proof_adapter/status once"}, 503)
        return True
    _setup()
    q = {k: v[0] for k, v in urllib.parse.parse_qs(u.query).items()}
    body = {}
    if method == "POST":
        try:
            n = int(h.headers.get("Content-Length") or 0)
        except ValueError:
            n = 0
        if n > MAX_BODY:
            _send(h, {"error": "body_too_large", "max_bytes": MAX_BODY}, 413)
            return True
        try:
            body = json.loads(h.rfile.read(n).decode("utf-8") or "{}") if n else {}
            if not isinstance(body, dict):
                body = {}
        except Exception:
            _send(h, {"error": "bad_json"}, 400)
            return True
    key = h.headers.get("X-Sebbi-Key") or body.get("key") or q.get("key")
    try:
        out, code = table[name](q, body, key)
    except Exception as e:
        out, code = {"error": "failed", "detail": str(e)[:160]}, 500
    _send(h, out, code)
    return True


def _find_handler_class(ctx):
    if isinstance(ctx, dict):
        for k in ("handler_class", "handler", "Handler", "h", "request_handler"):
            v = ctx.get(k)
            if v is None:
                continue
            cls = v if isinstance(v, type) else type(v)
            if hasattr(cls, "do_GET"):
                return cls
    f = sys._getframe()
    while f is not None:
        s = f.f_locals.get("self")
        if s is not None and hasattr(type(s), "do_GET") and hasattr(s, "wfile"):
            return type(s)
        f = f.f_back
    return None


def _install(ctx):
    global _patched
    if isinstance(ctx, dict) and "conn" in ctx:
        _ctx.update(ctx)
        _setup()
        _load()
        _start_loop()
    if _patched:
        return True
    cls = _find_handler_class(ctx)
    if cls is None:
        return False
    if getattr(cls, "_ppa_patched", False):
        _patched = True
        return True
    og, op, oo = cls.do_GET, getattr(cls, "do_POST", None), getattr(cls, "do_OPTIONS", None)

    def do_GET(self):
        path = self.path.split("?")[0].split("#")[0].rstrip("/") or "/"
        hit = _FILES.get(path)
        if hit:
            body, ctype, fname = hit
            self.send_response(200)
            self.send_header("Content-Type", ctype)
            self.send_header("Content-Length", str(len(body)))
            if fname:
                self.send_header("Content-Disposition", 'attachment; filename="%s"' % fname)
            self.send_header("Cache-Control", "no-cache")
            self.end_headers()
            self.wfile.write(body)
            return
        if (self.path == "/p" or self.path.startswith("/p/")) and _run(self, "GET"):
            return
        return og(self)

    def do_POST(self):
        if self.path.startswith("/p/") and _run(self, "POST"):
            return
        return op(self) if op else None

    def do_OPTIONS(self):
        if self.path.startswith("/p/"):
            self.send_response(204)
            self.send_header("Access-Control-Allow-Origin", "*")
            self.send_header("Access-Control-Allow-Headers", "Content-Type, X-Sebbi-Key")
            self.send_header("Access-Control-Allow-Methods", "GET, POST, OPTIONS")
            self.send_header("Content-Length", "0")
            self.end_headers()
            return
        return oo(self) if oo else None

    cls.do_GET = do_GET
    if op:
        cls.do_POST = do_POST
    cls.do_OPTIONS = do_OPTIONS
    cls._ppa_patched = True
    _patched = True
    return True


def _flat(d):
    if not isinstance(d, dict):
        return {}
    return {k: (v[0] if isinstance(v, list) and v else v) for k, v in d.items()}


def handle(method, action, data, api_key, ctx):
    armed = _install(ctx)
    action = (action or "status").strip("/").lower()
    data = _flat(data)
    if "conn" in _ctx and action in POSTS and method == "POST":
        return POSTS[action](data, data, api_key or data.get("key"))
    if "conn" in _ctx and action in GETS and action not in ("",):
        return GETS[action](data, data, api_key)
    last = _latest_sth() if "conn" in _ctx else None
    if last:
        last.pop("ts", None)
    return {"module": "public_proof_adapter", "version": VERSION, "armed": armed,
            "aliases": ALIASES, "tree_size": len(_leaves), "latest_sealed_tree_head": last,
            "checkpoint_every_seconds": CHECKPOINT_SECONDS, "checkpoint_every_leaves": CHECKPOINT_EVERY,
            "open_submissions": OPEN, "spec": SPEC,
            "pages": sorted(_FILES.keys()),
            "endpoints": ["POST /p/submit", "/p/receipt", "/p/proof", "/p/consistency", "/p/sth", "/p/find"]}, 200


def register(MODULE_MAP):
    """For name-based loaders: map this module under its own name and its aliases."""
    mod = sys.modules[__name__]
    for name in ["public_proof_adapter"] + ALIASES:
        MODULE_MAP.setdefault(name, mod)
    return MODULE_MAP
